### ISSUE TITLE
No indication on connectivity failures

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#10]
If the ESP crashes on configuration save, there's only a brief moment of LED being dark as an indication of failed configuration. 

User can proceed to configure the WiFi unaware that his configuration was never saved.

Same applies to mistyped URLs

**Comment by DG12** [comment]
Can this be considered as pending Rev .A2 (?) of the board which includes an LED ? Is that planned?

**Comment by ojousima** [comment]
> Can this be considered as pending Rev .A2 (?) of the board which includes an LED ? Is that planned?

Yes, that's why this has been assigned to milestone 1.3
