### ISSUE TITLE
The network watchdog timer timeout is disabled when configuration mode is activated

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#1019]
When the browser opens the Configuration Wizard, the gateway enters configuration mode. While the browser is active, the gateway does not relay data. Gateway must be rebooted by the network watchdog timeout after 1 hour (in case the user forgot to close the browser with the configuration wizard).

**Comment by markoaamunkajo** [comment]
Leave browser open for 1 hour and after 1 hour GW should switch to normal mode, connect to cloud,
Browser should report lost connection

**Comment by markoaamunkajo** [comment]
QA passed
