### ISSUE TITLE
HTTP: how to interpret the "data" field of the sent messages

### ISSUE THREAD

**Issue by eti-ocb** [ruuvi/ruuvi.gateway_esp.c#1024]
Is there a documentation of the Cloud/HTTP(s) messages/protocol ? In particular, how to interpret the "data" field ? 

```
{
    "data": {
        "coordinates": "",
        "timestamp": 1712750062,
        "nonce": 1883045647,
        "gw_mac": "CC:82:09:0E:D9:05",
        "tags": {
            "DA:77:B2:94:F8:79": {
                "rssi": -65,
                "timestamp": 1712750061,
                "data": "0201061BFF99040506C56988B7D2003C0018040495D6E44715DA77B294F879"
            },
        }
    }
}
```

**Comment by Scrin** [comment]
The data field is the raw data from the tag, and thus it's dependent on the tag firmware. You'll likely be seeing data format 5 (which is in the sample you posted), which is documented here: https://docs.ruuvi.com/communication/bluetooth-advertisements/data-format-5-rawv2

**Comment by jheba** [comment]
If you mean the embedded one here >> https://github.com/ruuvi/ruuvi-sensor-protocols/blob/master/dataformat_05.md

**Comment by ojousima** [comment]
The MQTT format is documented at https://docs.ruuvi.com/gw-data-formats/mqtt-time-stamped-data-from-bluetooth-sensors
