### ISSUE TITLE
HTTP endpoint validation fails when 204 status code is returned

### ISSUE THREAD

**Issue by jheba** [ruuvi/ruuvi.gateway_esp.c#1047]
Hi guys,

While testing https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/1044 against IoT Hub HTTP endpoint, I discovered that validation fails when 204 http status code is returned.
![image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/290289/52dc1ca1-c4a5-4d26-8977-58ad4a52bff8)

Please consider whether 201 code should also be accepted in the validation process.

**Comment by ojousima** [comment]
Maybe all 2XX codes should be considered successful for validation?

**Comment by jheba** [comment]
+1 for all 2xx

**Comment by TheSomeMan** [comment]
Hi @jheba, 

Could you test the fix? You can update the firmware on your gateway by using this URL (the build on Jenkins build server): https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/1335/artifact/build/

**Comment by jheba** [comment]
Works fine! Thanks!
