### ISSUE TITLE
Prevent web browser from remembering API keys

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#1050]
[Link](https://github.com/ruuvi/ruuvi.gwui.html/issues/388)

**Comment by jheba** [comment]
Hmm... I intentionally created the issue in the [ruuvi.gwui.html](https://github.com/ruuvi/ruuvi.gwui.html) repo since, as far as I am aware, the change will apply to that repo only.
Should all issues, nevertheless which part of the gateway apply to, be reported here?

**Comment by TheSomeMan** [comment]
> Hmm... I intentionally created the issue in the [ruuvi.gwui.html](https://github.com/ruuvi/ruuvi.gwui.html) repo since, as far as I am aware, the change will apply to that repo only. Should all issues, nevertheless which part of the gateway apply to, be reported here?

Since ruuvi.gwui.html is included in this repo, we need to create a commit for the updated ruuvi.gwui.html. It's okay if you create an issue in ruuvi.gwui.html or in this repo. Sometimes several issues are fixed in ruuvi.gwui.html before updating ruuvi.gwui.html in this repo.

**Comment by TheSomeMan** [comment]
@jheba you can install the build with this fix from here: https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/1337/artifact/build/

**Comment by jheba** [comment]
Works great! Thanks!
