### ISSUE TITLE
send logs to remote syslog server

### ISSUE THREAD

**Issue by jheba** [ruuvi/ruuvi.gateway_esp.c#1056]
Hello,

I don't know if such feature is already on your roadmap, but it would be great to have possibility to send logs to remote syslog server.

AFAIK, currently the only way to access the logs is to have 
> ... the gateway connected to a computer or other usb host capable device in order to read the logs over USB. ...

(ref. https://f.ruuvi.com/t/ruuvi-gateway-logs-to-a-remote-syslog-server-the-diy-way/6130).

My gateway is going to be located nearly 2000 km away from me, so having logs exposed and sent to remote server, would greatly help to keep eye on the gateway.

**Comment by ojousima** [comment]
There is already issue #230 about this. We'll keep it in mind when we decide which new features to implement, but we already have telemetry data sent in a separate packet that can be configured to use any address: https://docs.ruuvi.com/gw-data-formats/http-gateway-status

Sending raw logs themselves would be pretty bandwidth-heavy, 100 MB / day or so, but of course there could be some kind of log-level system. Closing this issue for now, let's keep the discussion about it at #230
