### ISSUE TITLE
Failed to retrieve JSON file containing firmware update information. Server returned incorrect json: could not get latest/url

### ISSUE THREAD

**Issue by jheba** [ruuvi/ruuvi.gateway_esp.c#1061]
Hello,

FYI:
When clicking the "check" button with the default automatic firmware updates URL, I get the error:

![image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/290289/72cf1e8d-4978-4928-9be7-7d8db25e837f)

web browser console shows:
![image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/290289/918fe8fb-aaa6-47eb-8611-39a7e2235249)

**Comment by TheSomeMan** [comment]
This problem only occurs when "Automatic Updates" mode is set to "Manual updates only".

**Comment by jheba** [comment]
Indeed, the "manual updates only" was chosen.
