### ISSUE TITLE
Secure access through LAN 

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#117]
Currently hotspot is open for configuration while gateway is on LAN. 

Steps to take: 
1) Decide on what pages need authentication and what can be always open, e.g. reading metrics vs updating configuration settings

2) Decide on authentication method and password generation if applicable

3) Implement on UI

**Comment by ojousima** [comment]
Related, European Standard for IoT device security: https://www.etsi.org/deliver/etsi_en/303600_303699/303645/02.01.01_60/en_303645v020101p.pdf

Key takeaway: Passwords must be unique to each device and changeable.

**Comment by TheSomeMan** [comment]
@ojousima Currently REST API POST 'ap.json' and POST/DELETE 'connect.json' are allowed only for requests to 10.10.0.1, so they can be executed only from WiFi client which is connected to hotspot AP. 
So, it is not possible to change configuration from LAN, we can only see the connection status, '/metrics' and '/history'.
Do we still need to implement password protection? Or is the current implementation sufficient?
