### ISSUE TITLE
Post dataformat: Update docs to match upper-case, delimited MACs sent by gateway

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#118]
Adding the ":" in MACs resulted in bug with backend limitation of VARCHAR(16), let's keep the MACs in lower-case without delimiters everywhere where machines are reading them and convert to upper-case, ":" delimited version when shown to humans in UIs.

**Comment by ojousima** [comment]
EDIT, as the Ruuvi Station uses upper-case delimited format and backend is already fixed, it's easiest for everyone to just keep the upper-case delimited format. Rescoping this issue, docs.ruuvi.com needs to be updated with gateway post example that has "AA:BB:CC:DD:EE:FF"

**Comment by TheSomeMan** [comment]
@ojousima I've added description of MAC address format here: [https://docs.ruuvi.com/communication/ruuvi-network/backends/serverless/gateway-api#send-sensor-data](https://docs.ruuvi.com/communication/ruuvi-network/backends/serverless/gateway-api#send-sensor-data)

**Comment by ojousima** [comment]
Thanks, Closing
