### ISSUE TITLE
Coexistence support (future feature to minimise risk of saturating the BLE receiver)

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#12]
When ESP32 is transmitting, bypass the LNA or/and disable nRF52 receiver.

**Comment by ojousima** [comment]
Marking this as a 1.1 feature

**Comment by ojousima** [comment]
ESP32 has connection to LNA mode. To implement this, two things need to be done:
1) nRF52 LNA control must be implemented with pull-up
2) ESP32 must drive LNA_CRX down during WiFi TX activity.

**Comment by ojousima** [comment]
SKY66113-11 has 2 us turn-off time, so ESP32 should drive the LNA_CRX pin down at least 2 us before start of transmission. If it is possible, having a few microseconds more of margin would be useful. LNA_CRX can be released immediately after TX.

**Comment by ojousima** [comment]
@TheSomeMan the pin is `RB_GWBUS_LNA` defined in ruuvi.board.c/ruuvi_board_gwesp.h. Assigning this to you, please add unit test to verify that pin gets driven low on tx event if it can be done with reasonable effort. If the ESP32 stack handle LNA control, unit test could verify that the LNA configuration is passed to ESP32 stack but it's not necessary to simulate the stack WiFi events.

**Comment by TheSomeMan** [comment]
@ojousima I tried to find information on how to implement it, but without success.
wifi driver for ESP32 is a black box and I can't find API to catch wifi transmission event.
The only thing that I found is macro CONFIG_ESP32_WIFI_SW_COEXIST_ENABLE, which allows to partially control co-existance of wifi and internal bluetooth.
If you have any idea how to implement it, can you give me a clue?

**Comment by ojousima** [comment]
@TheSomeMan Maybe through multiple antenna configuration? https://github.com/espressif/esp-idf/issues/2768 . 
The "RX Antenna" would have `LNA_CRX` high and "TX Antenna" would have it low. In that case it would need to be verified that antenna GPIO is in RX Antenna mode most of the time. 

We're not sure if BLE LNA saturation really is a problem, so we can also push this issue further down in the roadmap if this seems to require a lot of work.
