### ISSUE TITLE
Make sure that Gateway's RTC will not drift too much

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#121]
Note that the ESP32 doesn't have an external 32kHz crystal populated and therefore RTC may drift between time synchronisations from internet time servers and this may cause unwanted logging behaviour.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/system_time.html

Questions to understand and make actions after that if needed:

- Which RTC clock source is currently used?

- How much is currently the worst case drifting in 24 hour in extreme temperatures (-40...+85C)?

- How many seconds of drifting are allowed in 24h?

**Comment by ojousima** [comment]
Crystals are accurate enough over a course of a single day, closing.
