### ISSUE TITLE
Add an HTTP-endpoint to be able to poll the latest data from the gateway using HTTP-GET

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#137]
https://f.ruuvi.com/t/ruuvi-sensors-ruuvi-gateway-home-assistant-easy/
https://f.ruuvi.com/t/ruuvi-sensors-ruuvi-gateway-home-assistant-easy/4445/5

**Comment by io53** [comment]
@TheSomeMan do you have any estimate when we could expect this feature to be implemented?

**Comment by ojousima** [comment]
It's a question of priorities, I think this could be assigned to milestone 1.6

**Comment by TheSomeMan** [comment]
@io53, I agree with @ojousima, it's a matter of priorities. 
Now I'm working on v1.3.1 and we have several versions in queue before v1.6: v1.3.2, v1.3.3, v1.4 and v1.5.
So, it's quite hard to predict now when it will be implemented.
But it's not a very difficult task, I think it can be implemented in 3-4 days (with unit-tests).
Maybe it's worth moving this task to v1.3.2 since there is related task #25 there, what do you think @ojousima?

**Comment by io53** [comment]
As for the format of the response, will it be about the same as the HTTP post body it currently sends?
The feature does not have to be implemented in the gateway for development of the HA integration to start as long as we have an idea of how the api will work :).

**Comment by TheSomeMan** [comment]
@io53 what do you think what format is more convenient?
we can send data in json format like in HTTP post body or in plain text like in "/metrics" endpoint

**Comment by io53** [comment]
Json would be a lot easier to work with for sure.

**Comment by TheSomeMan** [comment]
New HTTP-endpoint:
/history[&time=<interval_seconds>]
