### ISSUE TITLE
Postfix WiFi hotspot SSID with 4 last hex characters of ESP Mac

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#15]
This allows user to differentiate several gateways from one another

**Comment by laurijamsa** [comment]
Related to https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/46

So a name could be for example "Ruuvi Gateway F3D6".

**Comment by ojousima** [comment]
Assigned to @TheSomeMan
