### ISSUE TITLE
Add Finnish translations / update existing

### ISSUE THREAD

**Issue by hakunti** [ruuvi/ruuvi.gateway_esp.c#151]
![image](https://user-images.githubusercontent.com/25771106/102528505-5386ee80-40a7-11eb-8160-7b2d332b6988.png)

**Comment by hakunti** [comment]
![image](https://user-images.githubusercontent.com/25771106/102528553-639ece00-40a7-11eb-86d9-36f6f28fcc09.png)

**Comment by hakunti** [comment]
![image](https://user-images.githubusercontent.com/25771106/102528606-75807100-40a7-11eb-9af2-069d37c0350a.png)

**Comment by hakunti** [comment]
![image](https://user-images.githubusercontent.com/25771106/102528663-84672380-40a7-11eb-9158-96af6068e7f1.png)

**Comment by TheSomeMan** [comment]
@hakunti, could you please attach these messages as text in comments?

**Comment by hakunti** [comment]
Ruuvi Gateway on nyt valmiina käytettäväksi.
Näytä verkon tiedot
Piilota verkon tiedot
Katkaise yhteys
IP-osoite
Aliverkon peite
Oletysyhdyskäytävä


Haluatko varmasti katkaista yhteyden tähän verkkoon?
En Kyllä

Manuaalinen yhdistäminen
salasana
Yhdistetty onnistuneesti verkkoon "RuuviTag"
OK

**Comment by TheSomeMan** [comment]
Fixed in [ruuvi.gwui.html submodule](https://github.com/ruuvi/ruuvi.gwui.html/issues/30)
