### ISSUE TITLE
Add new text to connected to wi-fi page to make clear that gateway is ready

### ISSUE THREAD

**Issue by hakunti** [ruuvi/ruuvi.gateway_esp.c#153]
![image](https://user-images.githubusercontent.com/25771106/102529734-0441bd80-40a9-11eb-81fa-7d7c20f27823.png)

**Comment by hakunti** [comment]
Same added to issue #151

**Comment by TheSomeMan** [comment]
Fixed as part of [link](https://github.com/ruuvi/ruuvi.gwui.html/issues/30)
