### ISSUE TITLE
WiFi access point remains disabled after disconnecting the Ethernet cable

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#165]

**Comment by ojousima** [comment]
This was originally desired behavior, the WiFi hotspot would be turned off after Internet connection had been established. #117 is related, if the configuration WiFi is secured after first setup the WiFi / access point can be enabled after Ethernet disconnection

**Comment by TheSomeMan** [comment]
Yes, you're right, WiFi hotspot should be disabled after Ethernet disconnection, but only if the user has performed configuration.
In case if the user has just connected Ethernet cable, the Gateway is auto-configured and the hotspot is disabled, after Ethernet disconnection, hotspot remains disabled and after Gateway reset it is enabled again (there is no need to press and hold "Configure" button).

**Comment by TheSomeMan** [comment]
According to https://docs.ruuvi.com/gw-esp32-firmware/gw-esp32-wifi-hotspot this behavior is correct.
