### ISSUE TITLE
Seems unnecessarily "chatty" to browser after"ready to be used" - 1.3.1 - improvement

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.gateway_esp.c#170]
<img width="1280" alt="RuuviGateway 1 3 1-chatty" src="https://user-images.githubusercontent.com/2365961/104792429-61926280-576c-11eb-8766-9126f0e9dd28.png">
After being connected for a long time, if the browser is still connected to the gateway http packets keep coming at rate of 6 per second. See attached wireshark

**Comment by ojousima** [comment]
Since power or bandwidth isn't limited here, I don't really see any reason to take action on this.

**Comment by DG12** [comment]
Is this an indication of a problem?
In a wifi dense area this contributes to noise.
