### ISSUE TITLE
Status/Activity screen would be helpful  - 1.3.1 - improvement

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.gateway_esp.c#171]
It would be helpful if the there was a web page that displayed addition information like
version number!
last reset. mm/dd/yy hh:mm:ss
uptime :12:31  up 18:41, 5 Ruuvis, 2 non-Ruuvis, load averages: 187 217 216 packets/minute

total packets in/out

list of Ruuvi seen, last time packet was received from each and number of packets from it.

Destination configuration. ruuvi network/custom server;
custom server settings http:URL ,  MQTT server:PP, topic prefix...

Ruuvis / ALL Bluetooth devices

Wifi/ Etc

PS why is there even a [HIDE NETWORK INFO] ??

**Comment by ojousima** [comment]
Already done in Prometheus format, https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/78.

**Comment by DG12** [comment]
IMHO Prometheus for humans is "suboptimal" (aka ugly)

**Comment by DG12** [comment]
Please review the need for this.
Would have been hekpf
