### ISSUE TITLE
configured but no packets sent - 1.3.1 - defect

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.gateway_esp.c#172]
I configured to use the web server running on my laptop smacpro but no packets are seen (even by wire shark. other than browser packets)

From the  browser on smacpro system I can see ""network configuration screen"

**Comment by ojousima** [comment]
This is related to the simulator? It doesn't have other features than the configuration mockup

**Comment by DG12** [comment]
I thought 1.3.1 was. +/- functional .

**Comment by ojousima** [comment]
The simulator is only a tool for developing the UI, it's not intended to be alternative for the gateway.

**Comment by DG12** [comment]
I thought 1.31.1 was not a simulator

**Comment by ojousima** [comment]
It runs on GW hardware

**Comment by TheSomeMan** [comment]
Perhaps, it was caused by #182

**Comment by TheSomeMan** [comment]
[ruuvi.gwui.html: README.md: add instruction on how to test the data transfer to a http server](https://github.com/ruuvi/ruuvi.gwui.html/issues/53)
