### ISSUE TITLE
MQTT: Add MAC address of gateway as a ClientID

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#206]

**Comment by ojousima** [comment]
This can be worked on when convenient

**Comment by TheSomeMan** [comment]
@ojousima  perhaps it would be better to use "RuuviGatewayXXXX" as ClientID (the same name as WiFi AP and hostname), what do you think?

**Comment by ojousima** [comment]
Thee problem with name "RuuviGatewayXXXX" is that it has only 4 hex characters or 2 bytes of entropy, there would be collisions in names pretty soon.
