### ISSUE TITLE
HTTP: Add user + pass fields

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#21]

**Comment by TheSomeMan** [comment]
I have some questions
1. On what stage the user should configure user/pass? Before connecting to WiFi?
2. This user/pass should be stored in NVS together with WiFi settings (in "settings" blob)?
3. What are default values for user/pass?

**Comment by ojousima** [comment]
This is about using http basic authentication when user is sending data to a remote server, same way as MQTT has the user/pass fields. They should be configured in custom server settings, MQTT has similar fields.
<img width="669" alt="image" src="https://user-images.githubusercontent.com/2360368/87062302-8fbf4480-c215-11ea-9989-44e28b498cd3.png">

Default values are at https://docs.ruuvi.com/gw-esp32-firmware/gw-esp32-configuration, "" and "" (empty strings).
