### ISSUE TITLE
ESP-IDF: Update to v4.0

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#23]
Unless there's specific reason to use 4.0-rc instead of 4.0, let's fix the ESP-IDF to 4.0. Only change required is in README.

**Comment by jsaari** [comment]
There were breaking changes after 4.0-rc but they are fixed in 4.0 so this is fine. `Tcpip_adapter` was renamed to `esp_netif` but now there is compability layer.
