### ISSUE TITLE
API query history should be renamed latest - v1.3.1-43-g3e559dc - defect?

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.gateway_esp.c#231]
Since history (currently) only returns latest value the name should be changed to latest or last.

**Comment by ojousima** [comment]
History is related to home assistant support, home assistant needs only the latest data point. 
The point of the gateway is not to cache data locally, Ruuvi Network and other cloud backends are for that. 

Local history would be nice, but not effort/benefit ratio is not good enough to justify further work on this.
