### ISSUE TITLE
JSON response should not use TAB characters -  - v1.3.1-43-g3e559dc - improvement

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.gateway_esp.c#232]
It is unnecessary to "visually" align columns using [TAB] characters and it makes writing (non JSON aware) scripts awkward.

**Comment by ojousima** [comment]
Can you provide an example of JSON with tabs?

**Comment by DG12** [comment]
<pre>curl  http://192.168.1.63/history 2>/tmp/RuuviGatewatH.o --output history.210610_0815.txt

hexdump -C history.210610_0815.txt
00000000  7b 0a 09 22 64 61 74 61  22 3a 09 7b 0a 09 09 22  |{.."data":.{..."|
00000010  63 6f 6f 72 64 69 6e 61  74 65 73 22 3a 09 22 22  |coordinates":.""|
00000020  2c 0a 09 09 22 74 69 6d  65 73 74 61 6d 70 22 3a  |,..."timestamp":|
00000030  09 22 31 36 32 33 33 32  37 33 31 36 22 2c 0a 09  |."1623327316",..|
00000040  09 22 67 77 5f 6d 61 63  22 3a 09 22 32 34 3a 30  |."gw_mac":."24:0|
00000050  41 3a 43 34 3a 45 32 3a  44 38 3a 32 38 22 2c 0a  |A:C4:E2:D8:28",.|
00000060  09 09 22 74 61 67 73 22  3a 09 7b 0a 09 09 09 22  |.."tags":.{...."|
00000070  43 34 3a 44 38 3a 41 34  3a 41 39 3a 30 39 3a 38  |C4:D8:A4:A9:09:8|
00000080  31 22 3a 09 7b 0a 09 09  09 09 22 72 73 73 69 22  |1":.{....."rssi"|
</pre>
