### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#237]
Rewrite the readme.md so that it'll have all the necessary information available to flash and read console log using different operating systems. Explain how ESP is flashing the nRF and how long it may take. Avoid instructing users to find help from 3rd party websites. Remove redundant pin definition informations that are referring to devkits that were used a long time ago. Older than modified (R15 disconnected) Ruuvi Gateway A2 boards don't need to be supported in the documentation.

**Comment by whakey** [comment]
I would really like to know how to read any kind of logs from the device :) This would help a lot with diagnosing configuration issues, now I don't have any feedback at all.

Having trouble with connecting to Azure IoT Hub, see: https://f.ruuvi.com/t/gatewayn-liittaminen-azure-iot-hubiin/5447/3

**Comment by ojousima** [comment]
Gateway USB port has serial connectivity. You can connect to the serial port with e.g. PuTTY or Minicom and read the log output at 115200 baud

**Comment by markoaamunkajo** [comment]
QA passed
