### ISSUE TITLE
Implement blacklist/whitelist for sensor MAC addresses

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#238]
In some cases it would be beneficial to being able to define which Ruuvi sensors (or other nearby Bluetooth broadcast transmitters) to forward via HTTP/MQTT. Some reasons:

- Data plan and/or bandwidth of Gateway's internet connection is limited and too many Ruuvi or other BLE devices around
- Gateway is pushing data to a 3rd party server and unnecessary incoming data is causing extra load and requires additional filtering
- A 3rd party server is used and use case requires Gateway to stay quiet by default and send any data only if a certain predefined BLE device(s) comes in the range of the Gateway

**Comment by ojousima** [comment]
Moved to https://feedback.ruuvi.com/posts/28/make-it-possible-to-whitelist-mac-addresses-on-the-gateway-web-ui, let's see how much demand there is for this feature.

**Comment by laurijamsa** [comment]
I'm reopening this issue and let's keep it in the backlog until we've specified in better detail how it should actually work and look like.

**Comment by laurijamsa** [comment]
Just adding a note here that we just discussed with Aleksei about this issue and concluded that it would be better to filter on the nRF side and send in the nRF->ESP32 bus only broadcasts of the wanted beacons. I think filtering "route only Ruuvi sensors" is already doing it like this, meaning, if the Ruuvi filtering mode is on, no data of other nearby beacons are transferred from nRF to ESP32.

**Comment by ojousima** [comment]
While filtering on nRF52 would be better in principle, I'm a bit worried about the size of the whitelist nRF52 could hold. I can look into free resources if needed, RAM was really tight if I recall correctly

**Comment by ojousima** [comment]
nRF 52 resources
<img width="792" alt="image" src="https://user-images.githubusercontent.com/2360368/188802480-6f5d310a-c5dd-4306-876d-8e07ff3eb5ee.png">

**Comment by laurijamsa** [comment]
A user feedback:

"simple dashboard where all the MACs seen and would be able to pick from there would be nice. same kind of when you pick the wifi from list"

**Comment by Scrin** [comment]
How about including a toggle between whitelist and blacklist? Having a blacklist would support use cases where one wants to collect all advertisements, but ignore a few known "misbehaving" broadcasters. For example, my neighbor has a couple of what seems to be bluetooth speakers, which are broadcasting undirected advertisements at 100ms interval 24/7 which is too much unnecessary noise so I currently have to run in "ruuvi sensors only" mode

From implementation point of view I don't think it would require that much more work, since the "list management" would work the same for both modes, just the filtering condition would be flipped

**Comment by oh2th** [comment]
Indeed if there was in the Custom Server configuration a section for whitelisting and blacklisting.
Should it be an option to only use whitelisting or blacklisting, or some sort of combination? Maybe the first implementation could be for only one or the other.
Ideally selection based on heard devices list and allow adding MACs manually for those that are not in range at the time of configuration.

**Comment by ojousima** [comment]
Let's implement both white- and blacklist as a part of this issue

**Comment by markoaamunkajo** [comment]
Waiting for main card

**Comment by markoaamunkajo** [comment]
If configuration saved and then reconfigured too fast gateway may stop sending sensor data to cloud.
Discussed details on channel. Unsure if it's related to filtering or configuring in general.

**Comment by markoaamunkajo** [comment]
QA passed
