### ISSUE TITLE
Implement support for data transfer to the MQTT server without delay

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#242]

**Comment by ojousima** [comment]
Marking as 1.7 feature

**Comment by ojousima** [comment]
Slightly unrelated, but noting this for when we work on MQTT

Gateway running 1.4.0 stop sending values over mqtt. Green LED on (solid), wake up after power cycle. It has happen 2 times now.
Any other with the same experience ?
