### ISSUE TITLE
Public wifi join: discuss if it's worth it

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#253]
Description:

Configuring Ruuvi Gateway on MacOS currently tries to force using Public Wifi join window when joining Gateway wifi network.

It's hopelessly broken, ugly and shameful.
Let's discuss options how to make it work flawlessly for the next meeting.

- 20-30 seconds delay after connecting to gateway wifi before public wifi popup is opened
- Page formatting and styling not working. Languages are shown as mixed.

![photo_2021-06-27 11 59 35](https://user-images.githubusercontent.com/50437378/123533376-3199b300-d73f-11eb-97c2-babcdc6dc780.jpeg)

- Connecting to wifi network fails with various funky errors that makes no sense whatsoever
![photo_2021-06-27 11 59 37](https://user-images.githubusercontent.com/50437378/123533379-39f1ee00-d73f-11eb-8ba9-97d97e308e60.jpeg)
![photo_2021-06-27 12 10 29](https://user-images.githubusercontent.com/50437378/123533588-dbc60a80-d740-11eb-9a57-63c6215fd816.jpeg)

- The configurator tries to force opening it always in the public wifi window. Also, for some reason play.google.com address is shown at the browser (bottom).
![photo_2021-06-27 11 59 41](https://user-images.githubusercontent.com/50437378/123533399-66a60580-d73f-11eb-8cf5-e8b0cbe1a7ac.jpeg)

**Comment by ojousima** [comment]
This looks like a missing CSS issue, adding this to milestone 1.9. Let's push all UI improvements there

**Comment by laurijamsa** [comment]
We have decided to instruct users that their desktop or mobile browser may open the configuration wizard automatically but if not, then to open it manually. Closing this issue for now.
