### ISSUE TITLE
Possible to make configurator use Secure connection (https)?

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#254]
Description:

Gateway configurator page uses http addresses and it looks ugly when browser is reporting it as Not Secure.
Is it possible to make it secure?
<img width="378" alt="Screenshot 2021-06-27 at 12 10 45" src="https://user-images.githubusercontent.com/50437378/123533573-bc2ee200-d740-11eb-8708-3539c023b1f4.png">

**Comment by ojousima** [comment]
Not possible with reasonable amount of effort, when connecting to hotspot without Internet access SSL Cert cannot be verified
