### ISSUE TITLE
UI: HTTP/MQTT: Replace the target radio buttons with checkboxes

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#287]
In addition to HTTP / MQTT mode, add an usage mode where GW is pollable only. This is for Home Assistant users who don't want to push their data to external servers

**Comment by laurijamsa** [comment]
Just typing a note here that today in our meeting we discussed about replacing radio buttons with checkboxes. This would allow to use one or many ways to relay sensor data simultaneously.

* Ruuvi cloud
* HTTP
* MQTT
* Polling from LAN
