### ISSUE TITLE
Get gateway to work on ESP32-WROOM (4MB) 

### ISSUE THREAD

**Issue by lauritk** [ruuvi/ruuvi.gateway_esp.c#288]
I am trying to get Ruuvi Gateway to work on cheap ESP32 with 4MB flash. I was able to flash the firmware after changing the partitions (in the expense of the OTA paritions/feature). Configuration wizard worked after temporaly disabled RESET -button functionality. GW now sends init message to HTTP -service, but no sensor data. I beleave the GW can not read the RuuviTags? Any tips to get things working, or is it even possible with reasonable work? I am new with ESP32, so I might miss something.

Monitor repeats following:
```
...
I (1101964) ADV_POST_TASK: [adv_post_task] Advertisements in table: 0
I (1106025) ruuvi_gateway: [monitoring_task] free heap: 140048
I (1111964) ADV_POST_TASK: [adv_post_task] Advertisements in table: 0
I (1116025) ruuvi_gateway: [monitoring_task] free heap: 140048
```

**Comment by ojousima** [comment]
Hello, 

4 MB is probably too little for OTA partitions. I don't know if the firmware will run without OTA. 
You need a nRF52 or other Bluetooth device to send advertisement data via UART to ESP32

**Comment by lauritk** [comment]
Hi, it will run with small OTA partitions, but of course OTA won't work anymore. ESP32-WROOM contains bluetooth. I can read RuuviTags with the ESP32 RuuviCollector firmware. I guess, to get things working I should change the code to support embedded bluetooth device?

**Comment by ojousima** [comment]
> I guess, to get things working I should change the code to support embedded bluetooth device?

That should work

**Comment by ojousima** [comment]
Closing this issue as it is outside the scope of Ruuvi main project
