### ISSUE TITLE
Configuration UI redesign

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#290]
Make the layout fully responsive so that it'll work well on any display size (mobile, tablet, desktop).

Translation: Several strings have changed and no Finnish translations available for all of them. In this case, you can just duplicate the English strings and after the html is otherwise ready, someone will translate if to Finnish at once and we'll also double check the English grammar once all is otherwise ready.

PDF: 
[qw-config-v1-final.pdf](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/6937005/qw-config-v1-final.pdf)

![image](https://user-images.githubusercontent.com/1311912/128314117-a3f80013-8242-4ef6-b8d7-4e7749bf2deb.png)

Logo: 
[ruuvi-logo-2021.svg.zip](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/6937016/ruuvi-logo-2021.svg.zip)

**Comment by markoaamunkajo** [comment]
Issues #297 #298 #299 #301 opened for reference, might not be valid for new UI

**Comment by laurijamsa** [comment]
This is completed. From now on, let's open UI related issues on the correct repository.
