### ISSUE TITLE
Updating resets authentication

### ISSUE THREAD

**Issue by io53** [ruuvi/ruuvi.gateway_esp.c#293]
After updating to 1.7.0 from 1.6.0 I was denied access from LAN. Activating hotspot and re-doing the setup for each update should not be necessary.

**Comment by laurijamsa** [comment]
I tried to reproduce this by flashing 1.8.0dirty, configuring password protection to lan access and then let it update to 1.8.0 automatically. Lan access is still working but like issue https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/331 describes, it returns error firs time when pressed the login button. Could you @io53 confirm? If you can reproduce what I saw, we can close this issue and leave the #331 open.

**Comment by io53** [comment]
1.8.0 -> 1.8.1 remembers authentication in my tests. Closing
