### ISSUE TITLE
Gateway configuration: text alignment looks ugly

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#296]
Description:

Text alignment (justify) looks ugly on many pages in configuration.

![text_align](https://user-images.githubusercontent.com/50437378/129828032-4c04148e-148b-465b-afcc-458f315e0276.jpg)

**Comment by markoaamunkajo** [comment]
Might not be valid for new UI but for reference

**Comment by laurijamsa** [comment]
Closing, not related with the new UI. Let's review the new UI soon.
