### ISSUE TITLE
Gateway configuration: an informative and cool looking animation is missing

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#297]
Description:

There is a placeholder box for animation on first page of Gateway configurator, but there is no content.
Should this box be removed or is it waiting for content?

![Screenshot_20210818-091256_Chrome](https://user-images.githubusercontent.com/50437378/129828374-663375c8-68e4-4017-83c8-1e0bded93099.jpg)

**Comment by ojousima** [comment]
New UI design doesn't have animation, closing this.
