### ISSUE TITLE
Gateway configuration: Choosing language should bring me back to top of page

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#298]
Description:

User is opening gateway configurator page with mobile browser (Samsung S8, Chrome). On first page language selector is displayed, choosing Suomi will not bring me completely to the top of the page showing colourful banner, instead top is considered to be where the text begins.

![choose_language](https://user-images.githubusercontent.com/50437378/129828988-34a4e3c4-25ef-4c0d-865d-ef8a825e4e67.jpg)

**Comment by markoaamunkajo** [comment]
Might not be valid for new UI but for reference

**Comment by laurijamsa** [comment]
Closing, but feel free to reopen if still valid after the new UI has been polished otherwise.
