### ISSUE TITLE
Gateway configuration: missing language strings

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#299]
Description:

Some strings in configurator are not translated to Finnish language. Maybe these are in the language file (need to check these strings exist)
![strings_3](https://user-images.githubusercontent.com/50437378/129829562-f1677426-049a-4b06-8326-27b41144550b.jpg)
![strings_2](https://user-images.githubusercontent.com/50437378/129829575-bba2cf29-8723-4b8d-ac0d-d90ee5e8d8a1.jpg)
![strings_1](https://user-images.githubusercontent.com/50437378/129829576-3ba6d212-b3b1-4188-9b9d-e94fd6b75506.jpg)

**Comment by markoaamunkajo** [comment]
Might not be valid for new UI but for reference

**Comment by laurijamsa** [comment]
Closing. All the strings will be double checked in the next coming days.
