### ISSUE TITLE
ESP button functionality

### ISSUE THREAD

**Issue by nomadi** [ruuvi/ruuvi.gateway_esp.c#30]
Proposed functionality: when clicked, don't wipe out pre-existing settings, only make the hotspot mode available again. It's possible, for example, that the user wants to change the wifi network password, but wants to keep other details such as the same server details the same.

**Comment by jsaari** [comment]
It is functioning like that. Button press resets only the wifi settings and Ruuvi spesific settings are kept.

**Comment by laurijamsa** [comment]
So all should be fine. Let's open this if we experience problems...
