### ISSUE TITLE
Gateway configuration: encountered connection issue with Android

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#300]
Description:

User is downloading and updating firmware using Android mobile phone (Samsung S8).
On one occasion update was interrupted and user saw the following page.

User had selected manual URL to use in update.

![Screenshot_20210818-100237_Chrome](https://user-images.githubusercontent.com/50437378/129830473-e5a938b7-2b62-4bd9-8ca4-92fcc1407c3c.jpg)
![Screenshot_20210818-100108_Chrome](https://user-images.githubusercontent.com/50437378/129830483-2ff48310-05e8-4caf-9e5f-a69f186921f2.jpg)

**Comment by ojousima** [comment]
I wonder if this is a bug or GW reboot 🤔

**Comment by laurijamsa** [comment]
Closing, but let's reopen if we can reproduce this in the latest UI.
