### ISSUE TITLE
While using the configuration wizard, Gateway suddenly reboots

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#303]
When plugged in ethernet cable here, the Gateway rebooted (at least that's what I think it did because the window closed automatically and Wi-Fi hotspot disappeared).

![image](https://user-images.githubusercontent.com/1311912/130391954-525d75c2-6440-4d8d-8b78-5c476d426952.png)

After I tried again, same reboot happened on the last page where everything was ready. I was just reading instructions on the "gateway is now functional" page and it suddenly disappeared.

**Comment by TheSomeMan** [comment]
this problem was fixed, here are the binaries: https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/339/
