### ISSUE TITLE
Connecting ethernet cable does not allow to continue configuration

### ISSUE THREAD

**Issue by hakunti** [ruuvi/ruuvi.gateway_esp.c#305]
![image](https://user-images.githubusercontent.com/25771106/130440761-5bf32116-9866-4818-a05c-13f126f48634.png)

When ethernet cable is connect, it's not possible to continue configuration. Gateway connects to internet and it's not possible to click next.

**Comment by laurijamsa** [comment]
This has been fixed for me on the build https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/341/

**Comment by hakunti** [comment]
Fixed now

**Comment by TheSomeMan** [comment]
Fixed in https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/341/
