### ISSUE TITLE
After "gateway is functional" hotspot is closed automatically and user has no time to read the success page

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#306]
After ~10 seconds, this window disappears and hotspot is disconnected automatically. That's not a good user experience. 

<img width="662" alt="Screenshot 2021-08-23 at 20 48 10" src="https://user-images.githubusercontent.com/1311912/130493399-c707c910-db39-408d-9b99-87521dbc8383.png">

Log:

``` I (288910) gw_cfg: [http_server] Gateway SETTINGS:
I (288915) gw_cfg: [http_server] config: use eth: 1
I (288921) gw_cfg: [http_server] config: use eth dhcp: 1
I (288927) gw_cfg: [http_server] config: eth static ip: 
I (288933) gw_cfg: [http_server] config: eth netmask: 
I (288939) gw_cfg: [http_server] config: eth gw: 
I (288944) gw_cfg: [http_server] config: eth dns1: 
I (288950) gw_cfg: [http_server] config: eth dns2: 
I (288955) gw_cfg: [http_server] config: use mqtt: 0
I (288961) gw_cfg: [http_server] config: mqtt server: test.mosquitto.org
I (288968) gw_cfg: [http_server] config: mqtt port: 1883
I (288974) gw_cfg: [http_server] config: mqtt prefix: <SENSOR_MAC_ADDRESS>
I (288982) gw_cfg: [http_server] config: mqtt client id: EE:39:AD:AB:XX:XX
I (288989) gw_cfg: [http_server] config: mqtt user: 
I (288995) gw_cfg: [http_server] config: mqtt password: ********
I (289002) gw_cfg: [http_server] config: use http: 1
I (289007) gw_cfg: [http_server] config: http url: https://network.ruuvi.com/record
I (289016) gw_cfg: [http_server] config: http user: 
I (289021) gw_cfg: [http_server] config: http pass: ********
I (289028) gw_cfg: [http_server] config: LAN auth type: lan_auth_deny
I (289035) gw_cfg: [http_server] config: LAN auth user: 
I (289041) gw_cfg: [http_server] config: LAN auth pass: ********
I (289047) gw_cfg: [http_server] config: Auto update cycle: regular
I (289054) gw_cfg: [http_server] config: Auto update weekdays_bitmask: 0x7f
I (289062) gw_cfg: [http_server] config: Auto update interval: 00:00..24:00
I (289070) gw_cfg: [http_server] config: Auto update TZ: UTC+3
I (289076) gw_cfg: [http_server] config: coordinates: 
I (289082) gw_cfg: [http_server] config: use company id filter: 1
I (289089) gw_cfg: [http_server] config: company id: 0x0499
I (289095) gw_cfg: [http_server] config: use scan coded phy: 0
I (289101) gw_cfg: [http_server] config: use scan 1mbit/phy: 1
I (289108) gw_cfg: [http_server] config: use scan extended payload: 1
I (289115) gw_cfg: [http_server] config: use scan channel 37: 1
I (289122) gw_cfg: [http_server] config: use scan channel 38: 1
I (289128) gw_cfg: [http_server] config: use scan channel 39: 1
I (289136) ruuvi_gateway: [http_server] sending settings to NRF: use filter: 1, company id: 0x0499,use scan coded phy: 0,1
I (289157) ETH: [http_server] Using ETH DHCP
E (289162) ETH: [http_server] ../main/ethernet.c:116 {ethernet_update_ip_dhcp}: tcpip_adapter_dhcpc_start failed, err=204)
I (289178) ADV_POST_TASK: [http_server] adv_post_enable_retransmission
I (289185) wifi_manager: [http_server] wifi_manager_stop_ap
I (289191) wifi_manager: [wifi_manager] MESSAGE: ORDER_STOP_AP
I (289197) wifi_manager: [wifi_manager] Configure WiFi mode: Station
I (289205) wifi:station: 50:ed:3c:37:14:85 leave, AID = 1, bss_flags is 134259, bss:0x3ffdf50c
I (289213) wifi:new:<1,0>, old:<1,0>, ap:<1,0>, sta:<0,0>, prof:1
I (289219) wifi:mode : sta (94:b9:7e:5b:xx:xx)
I (289223) wifi_manager: [sys_evt] WIFI_EVENT_AP_STADISCONNECTED
I (289230) wifi_manager: [sys_evt] WIFI_EVENT_AP_STOP
I (289237) wifi_manager: [wifi_manager] MESSAGE: EVENT_AP_STA_DISCONNECTED
I (289243) ruuvi_gateway: [wifi_manager] callback: on_ap_sta_disconnected
I (289250) ADV_POST_TASK: [wifi_manager] adv_post_enable_retransmission
I (289258) dns_server: [wifi_manager] Send request to stop DNS-Server
E (289266) http_server: [http_server] ../components/esp32-wifi-manager/src/http_server.c:251 {write_content_from_flash}: 1
I (289298) terminal_log: -----ACK-----

I (289298) terminal_log: CMD: RE_CA_UART_SET_ALL

I (289298) terminal_log: ACK state: RE_CA_ACK_OK

I (289315) dns_server: [dns_server] Got signal STOP
I (289315) dns_server: [dns_server] Stop DNS Server ```

**Comment by hakunti** [comment]
Wifi configuration:  On windows, gateway window is opened to new tab on the Chrome browser. It won't close after gateway connection is lost (automatically ~10 seconds)
![image](https://user-images.githubusercontent.com/25771106/130504441-e530b335-3579-4b4a-86c1-7ff6c7f8ac6c.png)

**Comment by TheSomeMan** [comment]
Build artifacts: https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/344/

**Comment by laurijamsa** [comment]
The hotspot is still stopped automatically. Are you stopping it by purpose? The instruction text says:

"You can now close this window and disconnect from the Ruuvi Gateway conﬁguration Wi-Fi hotspot."

Log:

```
I (114579) ADV_POST_TASK: [adv_post_task] X-Ruuvi-Gateway-Rate: Change period from 10000 ms to 60000 ms
I (114583) LEDS: [adv_post_task] leds_indication_on_network_ok
I (114585) LEDS: [adv_post_task] LED: ON
I (122878) ruuvi_gateway: [main] free heap: 124368
I (130333) http_server: [http_server] There are no HTTP requests for status.json for 20000 ms
I (130333) http_server: [http_server] Stop WiFi AP
I (130337) wifi_manager: [http_server] wifi_manager_stop_ap
I (130343) wifi_manager: [wifi_manager] MESSAGE: ORDER_STOP_AP
I (130349) wifi_manager: [wifi_manager] Configure WiFi mode: Station
I (130357) wifi:station: 50:ed:3c:37:14:85 leave, AID = 1, bss_flags is 134259, bss:0x3ffdf5b8
I (130365) wifi:new:<1,0>, old:<1,0>, ap:<1,0>, sta:<0,0>, prof:1
I (130371) wifi:mode : sta (94:b9:7e:5b:xx:xx)
I (130375) wifi_manager: [sys_evt] WIFI_EVENT_AP_STADISCONNECTED
I (130381) wifi_manager: [sys_evt] WIFI_EVENT_AP_STOP
I (130388) wifi_manager: [wifi_manager] MESSAGE: EVENT_AP_STA_DISCONNECTED
I (130395) ruuvi_gateway: [wifi_manager] callback: on_ap_sta_disconnected
I (130402) ADV_POST_TASK: [wifi_manager] adv_post_enable_retransmission
I (130409) dns_server: [wifi_manager] Send request to stop DNS-Server
I (130443) dns_server: [dns_server] Got signal STOP
I (130443) dns_server: [dns_server] Stop DNS Server
 ```

**Comment by TheSomeMan** [comment]
In the previous version the hotspot is stopped intentionally after configuration is complete. I disabled this.
Now the hotspot is stopped because UI doesn't send any requests when the final page is displayed (the delay is about 1 minute).
I can turn on sending requests for status.json - it will prevent hotspot stopping.

**Comment by laurijamsa** [comment]
Ok, let's do that. Additionally, it would be good to stop the hotspot automatically after user has disconnected manually first. I assume that there is a timeout already defined for that, right? I mean, a timeout that stops hotspot automatically if no one is connected.

**Comment by TheSomeMan** [comment]
fixed in https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/346/

**Comment by laurijamsa** [comment]
Alexey on chat: "Currently the gateway reboots in such situation, I'd like to modify firmware so that it will just disable hotspot."

How should it work now? What's the delay before closing the hotspot after user manually disconnected from the hotspot? After finished the configuration setup and disconnected manually, I'm still able to reconnect to the hotspot. So it seems that it's not disabled instantly after I disconnect manually.

After about 1 minute had passed since I manually disconnected, I connected again to the hotspot, and I was able to read info.json without problems. Soon after I read the info.json, my laptop was disconnected from the hotspot automatically.

Using the build 346.

**Comment by TheSomeMan** [comment]
> How should it work now? What's the delay before closing the hotspot after user manually disconnected from the hotspot? After finished the configuration setup and disconnected manually, 

There are two timers:
1. Client disconnected from the Gateway's hotspot - 1 minute (for example, manual disconnect from Wi-Fi)
2. There are no requests for status.json - 20 seconds (configuration is completed or Configuration wizard is closed in browser)
In both cases Wi-FI Access Point is stopped and previous network connection is restored (Ethernet or Wi-Fi)

> I'm still able to reconnect to the hotspot. So it seems that it's not disabled instantly after I disconnect manually.

Yes, it will be active for 1 minute if Configuration wizard was not active or 20 seconds if it was active.
Instantly disconnection is not good, because sometimes connection with AP is lost and automatically recovered during scanning for available Wi-Fi networks (when "Wi-Fi network" page is active).

> After about 1 minute had passed since I manually disconnected, I connected again to the hotspot, and I was able to read info.json without problems. Soon after I read the info.json, my laptop was disconnected from the hotspot automatically.

Perhaps, the disconnection event may have been received with a slight delay, so you need to wait little longer after manual disconnection.
