### ISSUE TITLE
Allow local api access when using Ruuvi Cloud 

### ISSUE THREAD

**Issue by io53** [ruuvi/ruuvi.gateway_esp.c#315]
In 1.7.1 it is not possible to set authentication method when using Ruuvi Cloud. It would be nice to be able access the history api without sacrificing Ruuvi Cloud.

**Comment by ojousima** [comment]
https://github.com/ruuvi/ruuvi.gwui.html/issues/107 is related

**Comment by markoaamunkajo** [comment]
Moving to done
