### ISSUE TITLE
Ethernet cable connected -> full erase -> flash -> "Hard resetting via RTS pin" -> hotspot is started

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#330]
This is not an urgent issue but makes me wonder why this is happening and is there something we should fix on this? If I reset now manually by toggling the power cord, no hotspot is started.

![image](https://user-images.githubusercontent.com/1311912/131238799-51614004-25da-474d-9b7b-84ecec7ed351.png)

**Comment by laurijamsa** [comment]
Maybe related:

Henri Hakunti, [31. Aug 2021 at 10.20.05]:
I found an issue with 1.8.2 but it seems that gateway is working. After ESP flashing green light will be solid as long as I will open Putty. Immediately after I open Putty it will show wifi and gateway starts running. I think reset will also help but somehow Putty is acting as a reset

**Comment by TheSomeMan** [comment]
could you please clarify
you flashed with esptool.py and hotspot is started (as expected), then you disconnected / connected USB cable and hotspot wasn't started? What kind of USB was used? USB from PC/Mac or just USB power?

**Comment by laurijamsa** [comment]
Like the topic says, I first connected an Ethernet cable and then erased the flash (using esptool.py on macOS). Then I flashed a build and after flashing finished, esptool.py performed "a hard reset via RTS pin". 

I would have expected the Gateway to start functioning in Ethernet mode because the cable was connected. But instead, the Wi-Fi hotspot got started. That made me think that maybe the RTS reset isn't working like it should. Or what's the reason for this?

**Comment by hakunti** [comment]
When we are flashing gateways at the "factory" USB cable is not disconnected. After flashing with Windows ESP flashing tool we continue testing process after the flashing is complete. Power is coming from PC.

**Comment by TheSomeMan** [comment]
maybe a long press on the Configure button was made? 
When configuration is cleared by the long-pressing on the Configure button, WiFi hotspot is started even Ethernet cable is connected, but it will be automatically stopped after one minute in no one connected to it. 
This was done to avoid confusion - when users resets the configuration to factory settings with long-pressing on the Configure button, they would expect that WiFi hotspot is started to perform configuration. In previous versions you always need to remember if Ethernet is connected and disconnect it before clearing configuration. In the current version, the gateway works the same whether Ethernet is connected or not - hotspot is started, so users can perform configuration, but after one minute if Ethernet is connected, then the gateway will be configured automatically.

**Comment by laurijamsa** [comment]
>maybe a long press on the Configure button was made?

No. I did not press the button. I just reproduced this with 3 different HW units. I don't know about Henri's case, but I'm talking about the behaviour I opened this issue for. It is still not clear why the device doesn't enter to Ethernet mode after the RTS hard reset even the Ethernet cable is connected.

**Comment by TheSomeMan** [comment]
> No. I did not press the button.

> after the RTS hard reset 

RTS hard reset means that the Configure button was pressed for 5 seconds, right?

> It is still not clear why the device doesn't enter to Ethernet mode after the RTS hard reset even the Ethernet cable is connected.

It should enter to Ethernet mode after one minute.

**Comment by laurijamsa** [comment]
> RTS hard reset means that the Configure button was pressed for 5 seconds, right?

No. RTS hard reset is something what the esptool does after flashing is completed successfully

**Comment by TheSomeMan** [comment]
the key point here is this:

> I first connected an Ethernet cable and then erased the flash (using esptool.py on macOS).

so, all configuration was erased (like when the Configure button is pressed for 5 seconds).
When the configuration is erased, then WiFi hotspot is activated for one minute after reboot and if no one is connected to configure the gateway, then it starts Ethernet. This was done in such a way as to avoid confusion - when users resets the gateway configuration to initial state they would expect that the WiFi hotspot is activated to perform configuration. But if Ethernet cable is connected, then it will not be possible to configure the gateway if Ethernet mode is activated immediately after reboot (the hotspot will not be started and default settings will be applied automatically).

**Comment by TheSomeMan** [comment]
I rechecked git commits history and it seems that it was fixed in 1.8.0. Started from this version WiFi hotspot should not be activated if the configuration was erased by esptool and it will be activated only if the configuration was reset by the Configure button.

**Comment by markoaamunkajo** [comment]
Works for me, moving to done
