### ISSUE TITLE
Password authentication fails when tried first time, pressing LOG IN again fixes the issue

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#331]
When I press LOG IN button after typed my password, I get an error. Now, after I press LOG IN again, it works. Note that in this test my user name and password were both only 1 character long, but I tried also with longer user name and password, behaviour is the same.

![image](https://user-images.githubusercontent.com/1311912/131238980-7a0d21eb-7bed-4a78-ba06-822b9f86488e.png)

**Comment by markoaamunkajo** [comment]
Moving to done
