### ISSUE TITLE
Allow access from LAN by using the unique device ID as default password

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#352]
I think we don't have an issue for this. So I'm creating one.

**Comment by ojousima** [comment]
Edited title. 
Current functionality (1.8.x) is DENY ACCESS by default, desired functionality is 
User: "Admin" Password: <nRF52 ID String>, e.g. "AA:BB:CC:DD:EE:FF:00:11"

**Comment by markoaamunkajo** [comment]
Moving to done
