### ISSUE TITLE
1.8.2: MQTT reports offline status even it's reporting data of multiple sensors

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#377]
This is a user report on the public Telegram channel:

![image](https://user-images.githubusercontent.com/1311912/136657222-6bf8e787-87f9-4960-985f-8d0f67697af4.png)

![image](https://user-images.githubusercontent.com/1311912/136657212-3aceae22-9cc3-4434-9479-bafdc606c1eb.png)

**Comment by TheSomeMan** [comment]
The "offline" message is LWT (Last Will and Testament) message which is sent by the broker when there is some network problems. 
I suppose that the gateway was not able to establish connection with the MQTT broker.
