### ISSUE TITLE
MQTT: custom topic prefix is truncated

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#394]
1.8.3-15

Tested name devices/RuuviGateway/messages/events and checking the settings page after saving looks truncated. Maybe such long prefix is not supported?

<img width="777" alt="Screenshot 2021-10-24 at 16 56 51" src="https://user-images.githubusercontent.com/50437378/138589338-738949ef-8f52-4c43-a283-2082f547b1e0.png">

_Originally posted by @markoaamunkajo in https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/386#issuecomment-950296029_

**Comment by markoaamunkajo** [comment]
QA passed
