### ISSUE TITLE
MQTT: deadlock while stopping MQTT during saving configuration

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#396]

**Comment by markoaamunkajo** [comment]
Unfortunately looks like v1.8.3-25 doesn't solve this issue.
Steps:

User had previously saved configuration to use MQTT, then he flashed new firmware to Gateway

1. He proceeded to configure Gateway using local ethernet address.
2. On server settings page he sees previously saved MQTT config, he changes it to Ruuvi Cloud
3. After finishing he checks setting again, but it stays in MQTT

Same tested on Wifi and Ethernet. Gateway was also restarted from reset button at some point during test, makes no difference.

https://user-images.githubusercontent.com/50437378/139528045-2a029d18-4f89-4e8c-ad5a-acf7bf8d5c30.mov

**Comment by TheSomeMan** [comment]
It was probably caused by #405

**Comment by markoaamunkajo** [comment]
IDLE0 spotted in logs on 1.9.0
[loki.txt](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/7469207/loki.txt)

**Comment by TheSomeMan** [comment]
Last time is was happened after connecting to WiFi, it's another problem, it was fixed in 1.9.1, see #424

**Comment by markoaamunkajo** [comment]
Moving this one to done, no more IDLE0 reports in log
