### ISSUE TITLE
Hotspot: Configuration page not reachable on failed WiFi connect

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#40]
If user configures wrong password for WiFi, hotspot remains active but user can no longer reach configuration page at 10.10.0.1.

Desired behavior is to let user to reconnect and reconfigure WiFi

**Comment by TheSomeMan** [comment]
I can't reproduce this problem (tried with different WiFi APs - a router and mobile hotspot on iphone).
1. reset configuration on the device
2. enter wrong password
3. try to reload configuration page - works as expected

Here are logs:
`
I (1755) wifi_manager: wifi_manager: Start DHCP client for STA interface. If not already running
I (1855) phy: phy_version: 4180, cb3948e, Sep 12 2019, 16:39:13, 0, 0
I (1855) wifi:mode : sta (30:ae:a4:02:84:a4)
I (1855) wifi_manager: WIFI_EVENT_STA_START
I (1855) wifi_manager: MESSAGE: ORDER_LOAD_AND_RESTORE_STA
I (1865) wifi_manager: wifi_manager_fetch_wifi_sta_config: ssid: password:
I (1865) wifi_manager: wifi_manager_fetch_wifi_settings: SoftAP_ssid:RuuviConfiguration
I (1875) wifi_manager: wifi_manager_fetch_wifi_settings: SoftAP_pwd:ruuvidongle
I (1885) wifi_manager: wifi_manager_fetch_wifi_settings: SoftAP_channel:1
I (1895) wifi_manager: wifi_manager_fetch_wifi_settings: SoftAP_hidden (1 = yes):0
I (1905) wifi_manager: wifi_manager_fetch_wifi_settings: SoftAP_bandwidth (1 = 20MHz, 2 = 40MHz)1
I (1915) wifi_manager: wifi_manager_fetch_wifi_settings: sta_only (0 = APSTA, 1 = STA when connected):1
I (1925) wifi_manager: wifi_manager_fetch_wifi_settings: sta_power_save (1 = yes):0
I (1935) wifi_manager: wifi_manager_fetch_wifi_settings: sta_static_ip (0 = dhcp client, 1 = static ip):0
I (1945) wifi_manager: wifi_manager_fetch_wifi_settings: sta_static_ip_config: IP: 0.0.0.0 , GW: 0.0.0.0 , Mask: 0.0.0.0
I (1955) wifi_manager: wifi_manager_fetch_wifi_settings: sta_ip_addr: 0.0.0.0
I (1955) wifi_manager: wifi_manager_fetch_wifi_settings: sta_gw_addr: 0.0.0.0
I (1965) wifi_manager: wifi_manager_fetch_wifi_settings: sta_netmask: 0.0.0.0
I (1975) wifi_manager: No saved wifi found on startup. Starting access point.
I (1985) wifi_manager: MESSAGE: ORDER_START_AP
I (1985) wifi:mode : sta (30:ae:a4:02:84:a4) + softAP (30:ae:a4:02:84:a5)
I (1995) wifi:Total power save buffer number: 16
I (1995) wifi:Init max length of beacon: 752/752
I (2005) wifi:Init max length of beacon: 752/752
I (2005) wifi_manager: WIFI_EVENT_AP_START
D (2015) wifi_manager: MESSAGE: ORDER_START_WIFI_SCAN
I (2015) eth: Using ETH DHCP
I (2025) eth: ETH ip updated
E (2525) emac_esp32: emac_esp32_init(303): reset timeout
E (2525) esp_eth: esp_eth_driver_install(192): init mac failed
E (2525) eth: Ethernet driver install failed
I (2525) ruuvidongle: Main started
I (2535) ruuvidongle: reset task started
I (2535) ruuvidongle: free heap: 161016
D (4465) wifi_manager: WIFI_EVENT_SCAN_DONE
D (4465) wifi_manager: MESSAGE: EVENT_SCAN_DONE
I (4465) dns_server: DNS Server listening on 53/udp
I (4465) http_server: HTTP Server listening on 80/tcp
I (12015) uart: advertisements in table:
I (12545) ruuvidongle: free heap: 140628
I (22015) uart: advertisements in table:
I (22545) ruuvidongle: free heap: 140628
I (29945) wifi:new:<1,0>, old:<1,0>, ap:<1,0>, sta:<0,0>, prof:1
I (29945) wifi:station: 74:e5:f9:c9:3f:8d join, AID=1, bgn, 20
I (30005) wifi_manager: WIFI_EVENT_AP_STACONNECTED
I (30005) tcpip_adapter: softAP assign IP to station,IP is: 10.10.0.2
I (32015) uart: advertisements in table:
I (32545) ruuvidongle: free heap: 130812
W (33475) http_server: netconn recv: -15
W (33475) http_server: the connection was closed by the client side
I (42015) uart: advertisements in table:
I (42545) ruuvidongle: free heap: 135696
I (49475) wifi_manager: MESSAGE: ORDER_CONNECT_STA
I (49605) wifi:new:<1,0>, old:<1,0>, ap:<1,0>, sta:<1,0>, prof:1
I (50575) wifi:state: init -> auth (b0)
I (50585) wifi:state: auth -> assoc (0)
I (50585) wifi:state: assoc -> run (10)
I (50665) wifi:state: run -> init (2c0)
I (50665) wifi:new:<1,0>, old:<1,0>, ap:<1,0>, sta:<1,0>, prof:1
I (50665) wifi:new:<1,0>, old:<1,0>, ap:<1,0>, sta:<1,0>, prof:1
I (50665) wifi_manager: WIFI_EVENT_STA_DISCONNECTED
I (50675) wifi_manager: MESSAGE: EVENT_STA_DISCONNECTED with Reason code: 15
I (50685) wifi_manager: Set STA IP String to: 0.0.0.0
I (50685) wifi_manager: uxBits & WIFI_MANAGER_REQUEST_STA_CONNECT_BIT
W (50695) ruuvidongle: Wifi disconnected
I (50695) LEDS: stop led blinking
I (50705) LEDS: start led blinking, interval: 1000 ms
I (52015) uart: advertisements in table:
I (52545) ruuvidongle: free heap: 135716
I (62015) uart: advertisements in table:
I (62545) ruuvidongle: free heap: 135716
`

But after entering a good password, http server stops working:
`
I (521325) wifi_manager: MESSAGE: ORDER_CONNECT_STA
I (521455) wifi:new:<1,0>, old:<1,0>, ap:<1,0>, sta:<1,0>, prof:1
I (522425) wifi:state: init -> auth (b0)
I (522435) uart: advertisements in table:
I (522445) wifi:state: auth -> assoc (0)
I (522455) wifi:state: assoc -> run (10)
I (522485) wifi:connected with iPhoneAlex, aid = 1, channel 1, BW20, bssid = 6e:13:81:ea:12:cf
I (522485) wifi:security: WPA2-PSK, phy: bgn, rssi: -43
I (522485) wifi:pm start, type: 0

I (522495) wifi_manager: WIFI_EVENT_STA_CONNECTED
I (522545) ruuvidongle: free heap: 135072
I (522675) wifi:AP's beacon interval = 307200 us, DTIM period = 1
I (523435) wifi_manager: IP_EVENT_STA_GOT_IP
I (523435) tcpip_adapter: sta ip: 172.20.10.10, mask: 255.255.255.240, gw: 172.20.10.1
I (523435) wifi_manager: MESSAGE: EVENT_STA_GOT_IP
I (523445) wifi_manager: Set STA IP String to: 172.20.10.10
I (523445) wifi_manager: About to save config to flash
D (523475) wifi_manager: wifi_manager_wrote wifi_sta_config: ssid:iPhoneAlex password:qwer{[<"
D (523475) wifi_manager: wifi_manager_wrote wifi_settings: SoftAP_ssid: RuuviConfiguration
D (523475) wifi_manager: wifi_manager_wrote wifi_settings: SoftAP_pwd: ruuvidongle
D (523485) wifi_manager: wifi_manager_wrote wifi_settings: SoftAP_channel: 1
D (523495) wifi_manager: wifi_manager_wrote wifi_settings: SoftAP_hidden (1 = yes): 0
D (523505) wifi_manager: wifi_manager_wrote wifi_settings: SoftAP_bandwidth (1 = 20MHz, 2 = 40MHz): 1
D (523515) wifi_manager: wifi_manager_wrote wifi_settings: sta_only (0 = APSTA, 1 = STA when connected): 1
D (523525) wifi_manager: wifi_manager_wrote wifi_settings: sta_power_save (1 = yes): 0
D (523525) wifi_manager: wifi_manager_wrote wifi_settings: sta_static_ip (0 = dhcp client, 1 = static ip): 0
D (523535) wifi_manager: wifi_manager_wrote wifi_settings: sta_ip_addr: 0.0.0.0
D (523545) wifi_manager: wifi_manager_wrote wifi_settings: sta_gw_addr: 0.0.0.0
D (523555) wifi_manager: wifi_manager_wrote wifi_settings: sta_netmask: 0.0.0.0
I (523565) ruuvidongle: Wifi connected
I (523565) LEDS: stop led blinking
I (523565) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (523575) ruuvidongle: Mac address: 30aea40284a4
I (523585) time: Synchronizing SNTP
I (523585) time: Waiting for system time to be set... (1/20)
I (526595) time: SNTP Synchronized: Thu Jun 25 12:01:26 2020
I (532455) uart: advertisements in table:
I (532545) ruuvidongle: free heap: 155584
I (542455) uart: advertisements in table:
I (542545) ruuvidongle: free heap: 155588
I (552455) uart: advertisements in table:
I (552545) ruuvidongle: free heap: 150092
I (562455) uart: advertisements in table:
I (562545) ruuvidongle: free heap: 150092
I (572455) uart: advertisements in table:
I (572545) ruuvidongle: free heap: 150092
I (582455) uart: advertisements in table:
I (582545) ruuvidongle: free heap: 150092
I (592455) uart: advertisements in table:
I (592545) ruuvidongle: free heap: 150092
I (602455) uart: advertisements in table:
I (602545) ruuvidongle: free heap: 150092
I (612455) uart: advertisements in table:
I (612545) ruuvidongle: free heap: 150092
`

**Comment by TheSomeMan** [comment]
But after entering a good password, http server stops working:

I (521325) wifi_manager: MESSAGE: ORDER_CONNECT_STA
I (521455) wifi:new:<1,0>, old:<1,0>, ap:<1,0>, sta:<1,0>, prof:1
I (522425) wifi:state: init -> auth (b0)
I (522435) uart: advertisements in table:
I (522445) wifi:state: auth -> assoc (0)
I (522455) wifi:state: assoc -> run (10)
I (522485) wifi:connected with iPhoneAlex, aid = 1, channel 1, BW20, bssid = 6e:13:81:ea:12:cf
I (522485) wifi:security: WPA2-PSK, phy: bgn, rssi: -43
I (522485) wifi:pm start, type: 0

I (522495) wifi_manager: WIFI_EVENT_STA_CONNECTED
I (522545) ruuvidongle: free heap: 135072
I (522675) wifi:AP's beacon interval = 307200 us, DTIM period = 1
I (523435) wifi_manager: IP_EVENT_STA_GOT_IP
I (523435) tcpip_adapter: sta ip: 172.20.10.10, mask: 255.255.255.240, gw: 172.20.10.1
I (523435) wifi_manager: MESSAGE: EVENT_STA_GOT_IP
I (523445) wifi_manager: Set STA IP String to: 172.20.10.10
I (523445) wifi_manager: About to save config to flash
D (523475) wifi_manager: wifi_manager_wrote wifi_sta_config: ssid:iPhoneAlex password:qwer{[<"
D (523475) wifi_manager: wifi_manager_wrote wifi_settings: SoftAP_ssid: RuuviConfiguration
D (523475) wifi_manager: wifi_manager_wrote wifi_settings: SoftAP_pwd: ruuvidongle
D (523485) wifi_manager: wifi_manager_wrote wifi_settings: SoftAP_channel: 1
D (523495) wifi_manager: wifi_manager_wrote wifi_settings: SoftAP_hidden (1 = yes): 0
D (523505) wifi_manager: wifi_manager_wrote wifi_settings: SoftAP_bandwidth (1 = 20MHz, 2 = 40MHz): 1
D (523515) wifi_manager: wifi_manager_wrote wifi_settings: sta_only (0 = APSTA, 1 = STA when connected): 1
D (523525) wifi_manager: wifi_manager_wrote wifi_settings: sta_power_save (1 = yes): 0
D (523525) wifi_manager: wifi_manager_wrote wifi_settings: sta_static_ip (0 = dhcp client, 1 = static ip): 0
D (523535) wifi_manager: wifi_manager_wrote wifi_settings: sta_ip_addr: 0.0.0.0
D (523545) wifi_manager: wifi_manager_wrote wifi_settings: sta_gw_addr: 0.0.0.0
D (523555) wifi_manager: wifi_manager_wrote wifi_settings: sta_netmask: 0.0.0.0
I (523565) ruuvidongle: Wifi connected
I (523565) LEDS: stop led blinking
I (523565) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (523575) ruuvidongle: Mac address: 30aea40284a4
I (523585) time: Synchronizing SNTP
I (523585) time: Waiting for system time to be set... (1/20)
I (526595) time: SNTP Synchronized: Thu Jun 25 12:01:26 2020
I (532455) uart: advertisements in table:
I (532545) ruuvidongle: free heap: 155584
I (542455) uart: advertisements in table:
I (542545) ruuvidongle: free heap: 155588
I (552455) uart: advertisements in table:
I (552545) ruuvidongle: free heap: 150092
I (562455) uart: advertisements in table:
I (562545) ruuvidongle: free heap: 150092
I (572455) uart: advertisements in table:
I (572545) ruuvidongle: free heap: 150092
I (582455) uart: advertisements in table:
I (582545) ruuvidongle: free heap: 150092
I (592455) uart: advertisements in table:
I (592545) ruuvidongle: free heap: 150092
I (602455) uart: advertisements in table:
I (602545) ruuvidongle: free heap: 150092
I (612455) uart: advertisements in table:
I (612545) ruuvidongle: free heap: 150092

**Comment by ojousima** [comment]
This was reported by user, waiting for information on how to reproduce.

**Comment by ojousima** [comment]
Cannot be reproduced, maybe related to #9 . It's not clear if the connection to WiFi was successful. Closing.
