### ISSUE TITLE
The configuration is reset to the default value if the configuration wizard is closed before configuration is complete and Ethernet cable is connected

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#418]

**Comment by markoaamunkajo** [comment]
User had set a configuration to gateway previously and completed setup wizard.
In v1.9.0-8 user resets gateway from hardware button to access configuration via wifi, changes automatic updates to 2 weeks, sets on access settings allow access without password, moves to next page and then closes configuration window and disconnects by choosing another wifi, then accesses the configuration again over ethernet, no previous changes were saved.

**Comment by TheSomeMan** [comment]
> User had set a configuration to gateway previously and completed setup wizard. In v1.9.0-8 user resets gateway from hardware button to access configuration via wifi, changes automatic updates to 2 weeks, sets on access settings allow access without password, moves to next page and then closes configuration window and disconnects by choosing another wifi, then accesses the configuration again over ethernet, no previous changes were saved.
> 
> Is this the expected behavior @TheSomeMan ?

The configuration is saved to the gateway when the user reaches the last page of the configuration wizard (but the network settings is saved when user selects WiFi/Ethernet). If the configuration wizard was closed before completing of the configuration process, then the changes will be lost.

**Comment by markoaamunkajo** [comment]
QA passed
