### ISSUE TITLE
User saves http server config with non-empty username and it shows Ruuvi cloud selected next time

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#422]
Description:

User had configured gateway to use MQTT server previously. He goes to configure settings again and now chooses http server and unselects MQTT, finishes configuration

Then he opens configurator again
Actual: Ruuvi cloud is now selected

**Comment by ojousima** [comment]
What did you configure as http server?

**Comment by markoaamunkajo** [comment]
[http_server] config: use http: 1
I (797095) gw_cfg: [http_server] config: http url: https://network.ruuvi.com/record
I (797103) gw_cfg: [http_server] config: http user: marko
I (797109) gw_cfg: [http_server] config: http pass: ********

**Comment by markoaamunkajo** [comment]
Actually looks like I was also able to deselect both http and MQTT servers, choose Ruuvi cloud and in this case I see Ruuvi cloud is being used in log but if I go to configurator Ruuvi cloud is not selected.

**Comment by ojousima** [comment]
>  https://network.ruuvi.com/record

This is Ruuvi Cloud address, so I'd expect the UI to show Ruuvi Cloud as selected.

**Comment by markoaamunkajo** [comment]
Interesting. But a bit confusing for the end user.

**Comment by TheSomeMan** [comment]
> This is Ruuvi Cloud address, so I'd expect the UI to show Ruuvi Cloud as selected.

Yes, that's right, when all settings are equal to "Ruuvi cloud" configuration, then it is selected automatically in UI.
But in this case not all settings are equal - http user/password are not equal to the default values (empty). Maybe we should take it into account.

**Comment by markoaamunkajo** [comment]
QA passed
