### ISSUE TITLE
Gateway does not see a WiFi hotspot created by a mobile phone

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#43]
Phone model: Galaxy S20 Ultra
Security: WPA2 PSK
Power saving mode: on by default "reduce battery usafe by analysing Mobile Hotspot traffic"

**Comment by laurijamsa** [comment]
Seems that after disabled manually the "power saving mode" on hotspot settings, the hotspot appeared to the configuration web interface.

**Comment by ojousima** [comment]
This is probably related to #44 , WiFi hotspots aren't refreshed after initial page load if I recall correctly. Assigning to @TheSomeMan

**Comment by ojousima** [comment]
@laurijamsa Is this issue still valid with this build: https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/57/artifact/build/? ref #54 #57

**Comment by ojousima** [comment]
Closing as stale
