### ISSUE TITLE
UI: Add a clarification where the user can get the default password for accessing from LAN

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#435]

**Comment by markoaamunkajo** [comment]
v1.9.2-RC1 I don't see the suggestion
<img width="711" alt="Screenshot 2021-12-07 at 19 41 53" src="https://user-images.githubusercontent.com/50437378/145031113-bf1b9233-bae4-44a1-adde-c9c87e5cc32c.png">

**Comment by ojousima** [comment]
Here is my view, it does have the info text
![image](https://user-images.githubusercontent.com/2360368/145032147-9ddfe2be-2f44-4a4e-a4f3-a8169191ace6.png)

**Comment by TheSomeMan** [comment]
@markoaamunkajo you need to select the first option "Password protected with the default password"

**Comment by markoaamunkajo** [comment]
@TheSomeMan is it possible that this only became visible to me after I did factory reset to my gw?

**Comment by ojousima** [comment]
@markoaamunkajo I get it without a factory reset too

**Comment by ojousima** [comment]
Marking this as done.
