### ISSUE TITLE
A WiFi hotspot remains visible on the configuration web UI's "choose a network list" even if the hotspot has been turned off

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#44]
Steps to reproduce:

1) Turn on a WiFi hotspot (for example on your mobile phone)

2) Connect to Ruuvi Gateway hotspot in order to configure it

3) The hotspot created by the phone is visible

4) Disable the hotspot

5) Refresh the configuration web page

6) The hotspot remains visible on the list

**Comment by laurijamsa** [comment]
This issue is also valid other way around. Meaning, if a WiFi hotspot will be activated when the web UI configuration page has been opened and then user refreshes the page in order to see the new hotspot on the list, the newly created hotspot doesn't appear on the list.

**Comment by ojousima** [comment]
Related to refreshing the scan results, see #43

**Comment by ojousima** [comment]
ref #43 #54 #57, is this still valid with build at https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/57/artifact/build/ @laurijamsa ?

**Comment by ojousima** [comment]
Closing as stale.
