### ISSUE TITLE
If connecting to a Wi-Fi network fails, user is suggested to try again but it's not possible to try again

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#441]
Sometimes connecting to a network fails like this:
<img width="701" alt="Screenshot 2021-11-24 at 20 50 03" src="https://user-images.githubusercontent.com/1311912/143311355-be24606a-9182-42f9-a42f-0b5a7c505716.png">

But it's not possible to try again by pressing the NEXT button because it's dim and not accessible. At this point, the only option is to press Back.
<img width="662" alt="Screenshot 2021-11-24 at 20 51 41" src="https://user-images.githubusercontent.com/1311912/143311367-422d0a0c-c07b-4c93-983c-359f3f230d89.png">

(Build 461)

**Comment by laurijamsa** [comment]
And when user clicks Back and tries to scan available networks again, scanning is not working:

https://user-images.githubusercontent.com/1311912/143312955-7e84c8a0-4d3f-40ba-bea6-0c82326e2381.mov

**Comment by laurijamsa** [comment]
It is opened but it's empty. My comment was about 0:09 when I select its radio button, it opens an empty dropdown. It seems like a mistake because it has no content. Would be better not to drop down an empty area when an open network is selected.

**Comment by markoaamunkajo** [comment]
v1.9.2-RC1 for open wifi network (I set my own AirPort Express) I can see it shows me first a weird password screen, then collapses and the issue disappears.

<img width="685" alt="Screenshot 2021-12-07 at 20 32 14" src="https://user-images.githubusercontent.com/50437378/145038400-455f2933-12d3-4d8a-89bb-65e67da62300.png">

**Comment by ojousima** [comment]
I can reproduce sometimes. First video is the whole UI getting stuck in some state

https://user-images.githubusercontent.com/2360368/145080728-877561c2-b574-4832-8486-e85d72706a37.mov

Second movie ends up working as expected, after fail I can reconnect. This can be repeated by connecting to a mobile hotspot and turning hotspot off right before clicking "next" to connect.

https://user-images.githubusercontent.com/2360368/145080876-81b5ebbe-d8c9-4337-917f-9d3c80d12fe3.mov

I don't think this blocks release though, we can discuss it in next meeting.

**Comment by ojousima** [comment]
Done, closing.
