### ISSUE TITLE
If user edits the password field and then decides he'd like to use defaults after all, it's not possible to return to the defaults

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#442]
https://user-images.githubusercontent.com/1311912/143315767-b04579b1-1899-47bc-95cf-57b8d2a0b0b7.mov

(Build 461)

**Comment by TheSomeMan** [comment]
It was closed in commit [83ba083](https://github.com/ruuvi/ruuvi.gateway_esp.c/commit/83ba083fffa6dd873e2b44c65b2e1d290d0ebd07)

**Comment by markoaamunkajo** [comment]
v1.9.2-RC1 this issue is still the same as in Lauri's video. Tested by completing a factory default reset and writing to same field, then switching between radio buttons after emptying default password field.

**Comment by TheSomeMan** [comment]
@markoaamunkajo UI was changed, the new option "Password protected with the default password" was added, so now user always can select it to return back to default username/password.

**Comment by ojousima** [comment]
@markoaamunkajo Please clarify? I can switch to default user with no issue as in video below
https://user-images.githubusercontent.com/2360368/145035864-00a16d43-4d38-48a1-b3e8-3a77b270efef.mov

**Comment by ojousima** [comment]
Marking this as done
