### ISSUE TITLE
Configuration hotspot reboots sometimes during the configuration

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#45]
This happens on a Ruuvi Gateway Rev.A1 board. Most probably related to the software.

**Comment by ojousima** [comment]
Steps to reproduce? Also as a context, @laurijamsa has prototype which overheats so this also might be HW related issue. I've had a board 20 minutes online in configuration mode with no reboots, you can verify the reboots with a terminal program such as minimum

**Comment by ojousima** [comment]
Closing as stale.
