### ISSUE TITLE
Gateway enters a boot loop if HTTP POST times out

### ISSUE THREAD

**Issue by Scrin** [ruuvi/ruuvi.gateway_esp.c#452]
If a user has configured to use HTTP with their own or 3rd party server and the said server goes down such that all requests time out, the gateway enters a boot loop, rebooting approximately every 10-20 seconds. This does not happen if the request simply fails, so it seems to be related to timeouts only.

This is extra problematic as you can't finish the configuration wizard to remove the http configuration before the gateway reboots. I ran into this issue after enabling the http post feature for testing, and then after leaving my test server off, I found that the gateway entered a reboot loop, uptime never exceeding 20 seconds.

Here are the metrics from the /metrics endpoint, you can see that the gateway was in a reboot loop from 2:30 to 04:00 when my test server was down, and another time around 12:40 when I took the test server down again. Probably unrelated but it also looks like the free heap was acting weird during the boot loop phase.

![image](https://user-images.githubusercontent.com/6617316/147821238-9e8d186f-c44c-4394-af69-58dabb882e7d.png)

**Comment by ojousima** [comment]
I'd guess that this is related to gateway watchdog. Was this with 1.8.X or 1.9.X FW? 1.9.X switched to asynchronous https calls to avoid task watchdog triggering, but 1.9.X had a regression where HTTP does not work due to ESP-IDF limitations

**Comment by Scrin** [comment]
It's v1.9.2, I have my gateway set for auto updates with the "for beta testers" option

**Comment by ojousima** [comment]
Thanks for the details. Let's get this fixed together with #449
