### ISSUE TITLE
Create a configuration file

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#454]
Some of our customers would greatly benefit of pre-configured Ruuvi Gateways. To be able to configure the devices during production, configuration registers should be possible to be written when flashing the ESP32. The most simple solution would be probably to have an additional file to be flashed:

- bootloader.bin
- fatfs_gwui.bin
- fatfs_nrf52.bin
- ota_data_initial.bin
- partition-table.bin
- ruuvi_gateway_esp.bin
- **config.bin (NEW FILE)**

We could offer also a public web page that allows users to easily generate desired configs.

**Comment by ojousima** [comment]
+1 for storing the config as plain JSON, I think the Gateway already does it for settings configured over the web configuration interface.

**Comment by ojousima** [comment]
A quick note:
New memory area for json files.
Factory setting file, settings are reset to it.
User setting file, user-configured / downloaded files are stored to it

**Comment by TheSomeMan** [comment]
@ojousima according to this task https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/456 I added CRC32 to the metrics endpoint, but CRC32 is calculated for the full configuration, while "/ruuvi.json" endpoint does not contain passwords, so it's not possible for the user to calculate/compare CRC32.

**Comment by TheSomeMan** [comment]
To test it:
1. Need to create an initial version of gw_cfg.json (use example from https://app.gitbook.com/o/-LsPfwGmkUWZFBz3qkE9/s/-LsPjfnhNj3v37AZtF-d/data-formats/gateway-configuration)
2. Configure WiFi in "wifi_sta_config"
3. Configure "remote_cfg_use", "remote_cfg_url", "remote_cfg_refresh_interval_minutes"
4. Run the local HTTP server and make this gw_cfg.json accessible
5. Configure gateway - on the Remote Configuration Download enable this feature and press Download button
6. Change something in gw_cfg.json (for example, enable MQTT)
7. Wait for a specified period ("remote_cfg_refresh_interval_minutes")
8. Check that the new configuration was downloaded and applied

**Comment by TheSomeMan** [comment]
To test it:

1. Need to create a custom default gateway configuration

Create a copy of "gw_cfg_default" folder, and modify gw_cfg_default.json as you require (for example, enable MQTT).
Execute command to generate binary gw_cfg_def.bin:
```
python $IDF_PATH/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py generate gw_cfg_def_partition.csv gw_cfg_def.bin 0x40000
```
2. Flash gw_cfg_def.bin

3. Crear configuration on Gateway by long pressing of the configure button

4. Check that custom default setting was applied

**Comment by ojousima** [comment]
Works well
