### ISSUE TITLE
Rename hotspot and use different default password

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#46]
Hotspot name: Ruuvi Gateway

Default password: 12345678

**Comment by laurijamsa** [comment]
Rename also device name that is currently "espressif" to Ruuvi Gateway.

**Comment by ojousima** [comment]
The rename is related to how your WiFi hotspot reports the gateway?

**Comment by ojousima** [comment]
As noted in #15, SSID should be e.g. `Ruuvi Gateway F3D6`

**Comment by TheSomeMan** [comment]
This task was fixed in #15, pull request #64
