### ISSUE TITLE
initial install difficulties  ESP_FW: v1.9.2

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.gateway_esp.c#470]
Attempt to startup gateway via wifi
11:14:30                RuuviGatewayFCC3 -58  1       Y  FI WPA2(PSK/AES,TKIP/TKIP)
Scan shows RuuviGatewayFCC3 but cannot join.
IP address assigned is 192.168.1.43
Cannot connect browser  to 192.168.1.43
nmap 192.168.1.43  reports 
-     80/tcp open  tcpwrapped
- | http-methods: 
- |_  Supported Methods: GET HEAD POST OPTIONS
- |_http-server-header: Ruuvi Gateway
- |_http-title: Did not follow redirect to http://10.10.0.1/

Attempt to connect browser  to 10.10.0.1 fails.. ( I have no LAN on 10.10.0.x)

11:14:30                RuuviGatewayFCC3 -58  1       Y  FI WPA2(PSK/AES,TKIP/TKIP)
I don't think this matters but I'm not in Finland.
I (2835) ruuvi_gateway: [main] WiFi country after esp_wifi_set_country: CC=**FI**, max_tx_power=11 dBm, schan=1, nchan=13, policy=AUTO

LOG follows

**Comment by DG12** [comment]
[screen220115 log](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/7889379/screen220115.log)

**Comment by ojousima** [comment]
Gateway does not start the hotspot if Ethernet is connected. 
The logs show that LAN access is disabled. 

To fix this, disconnected Ethernet cable and press the Gateway button under USB power source with a toothpick for 10 seconds to run a factory reset. After that the hotspot should come up and Gateway is accessible through LAN if you connect the Ethernet cable

**Comment by DG12** [comment]
I started without ethernet connection. Sorry I didn't take logs on first attempt.
I will reset and retry wifi with logs.

**Comment by DG12** [comment]
Held reset for a few seconds. No ethernet cable connected. Access point not available.

I (3155290) reset_task: [reset_task] The CONFIGURE button has been pressed - start timer for 5 seconds
I (3155291) LEDS: [reset_task] leds_indication_on_configure_button_press
I (3155297) LEDS: [reset_task] LED: Start blinking, interval: 500 ms, duty cycle: 50%
I (3160290) reset_task: [reset_task] System restart is activated by the Configure button
I (3160291) wifi_manager: [sys_evt] WIFI_EVENT_STA_STOP
I (3160294) wifi:flush txq
I (3160296) wifi:stop sw txq
I (3160300) wifi:lmac stop hw txq
ets Jul 29 2019 12:21:46
...
I (607) cpu_start: App version:      v1.9.2
I (612) cpu_start: Compile time:     **Dec  8 2021 16:05:15**
I (618) cpu_start: ELF file SHA256:  1b1c207622b8b3b7...
I (624) cpu_start: ESP-IDF:          v4.0.3
...

I (1849) wifi_manager: [main] WiFi manager init
I (1854) terminal_log: ACK state: RE_CA_ACK_OK

I (1860) wifi_manager: [main] Set STA IP String to: 0.0.0.0
I (1871) http_server: [main] Start HTTP-Server
I (1875) os_task: [main] Start thread 'http_server' with priority 4, stack size 20480 bytes
I (1884) http_server: [http_server] HTTP-Server thread started
I (1892) http_server: [http_server] HTTP Server listening on 80/tcp
I (1898) http_server: [http_server] TaskWatchdog: Create timer
I (1904) http_server: [http_server] TaskWatchdog: Register current thread
I (1912) http_server: [http_server] TaskWatchdog: Start timer
I (1919) wifi_manager: [main] WiFi manager init: start WiFi
I (1927) wifi:wifi driver task: 3ffd3898, prio:23, stack:6656, core=0
I (1931) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (1940) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (1956) wifi:wifi firmware version: 52d2120
I (1956) wifi:config NVS flash: enabled
I (1957) wifi:config nano formating: disabled
I (1962) wifi:Init data frame dynamic rx buffer num: 32
...
I (2687) wifi_manager: [main] wifi_manager: Start DHCP client for STA interface. If not already running
...
I (2813) ruuvi_gateway: [main] WiFi country after wifi_init: CC=CN , max_tx_power=11 dBm, schan=1, nchan=13, policy=AUTO
I (2824) wifi:set country: cc=FI^@ schan=1 nchan=13 policy=0
...
I (2829) ruuvi_gateway: [main] WiFi country after esp_wifi_set_country: CC=FI, max_tx_power=11 dBm, schan=1, nchan=13, policy=AUTO
I (2842) ruuvi_gateway: [main] Max WiFi TX power after wifi_init: 40 (10 dBm)
I (2849) ruuvi_gateway: [main] Max WiFi TX power after esp_wifi_set_max_tx_power: 32 (8 dBm)
I (2858) ETH: [main] Ethernet init
I (2863) ETH: [main] Using ETH DHCP.        +++++ NO ethernet cable attached+++
I (2867) ETH: [main] ETH ip updated
I (2873) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (2902) ETH: [main] Ethernet start
I (2912) ETH: [sys_evt] Ethernet Started
I (2913) ETH: [main] Set hostname for Ethernet interface: RuuviGatewayFCC3




complete log attached.
[GatewayFCC3.220118.1220.txt](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/7891139/GatewayFCC3.220118.1220.txt)

**Comment by DG12** [comment]
Tried again after reset, no access point, but after connecting to ethernet got it running:  
"DEVICE_ADDR":  "E1:43:48:48:FC:C3",
 "ESP_FW":   "v1.9.2",
   "NRF_FW":   "v0.7.2",
+++++++++++++ As this is for version 1.9.2  I provide these details BUT
I close this issue and will open a new issue if needed (hope not!)
Summary:
1) Access Point broadcasts but cannot join
2) ethernet connection gets login page but MacBookPro can't authenticate 
3) iPhone logs in over wifi (not to access Point) and successfully logs in
4) iPhone initiated firmware update and it completes successfully.
...
<pre>I (10400) TIME: [tiT] Time has been synchronized: 2022-01-19 19:13:40.491

I (12883) http: [adv_post_task] HTTP POST to URL=https://network.ruuvi.com/record, DATA:

I (29190) http_server: [http_server] There are no HTTP requests for status.json for 20000 ms
I (29190) http_server: [http_server] Stop WiFi AP
I (29193) wifi_manager: [http_server] wifi_manager_stop_ap
I (29200) wifi_manager: [wifi_manager] MESSAGE: ORDER_STOP_AP
I (29206) wifi_manager: [wifi_manager] Configure WiFi mode: Station
I (29214) wifi:mode : sta (94:b9:7e:59:a6:60)
I (29217) wifi_manager: [sys_evt] WIFI_EVENT_AP_STOP
... +++++++++++++++++++++++++++++++++++++=
Mac Book Pro Safari connects:
I (111480) http_server: [http_server] Request from 192.168.1.49 to 192.168.1.43: GET /
I (111481) http_server: [http_server] Extra HTTP-header resp: Set-Cookie: RUUVI_PREV_URL=/index.html
I (111487) http_server: [http_server] Respond: 302 Found
I (111515) http_server: [http_server] Request from 192.168.1.49 to 192.168.1.43: GET /auth.html
I (111518) http_server: [http_server] Respond: 401 Unauthorized
I (111549) http_server: [http_server] Request from 192.168.1.49 to 192.168.1.43: GET /crypto-js-4.0.0/core.js

...
I (111895) http_server: [http_server] Request from 192.168.1.49 to 192.168.1.43: GET /auth?_=1642619719585
I (111897) http_server: [http_server] Extra HTTP-header resp: WWW-Authenticate: x-ruuvi-interactive realm="RuuviGatewayFCC3"                 +challenge="51f5df60d5ea130a297999ca8a445c1d86c24b7566fb3d006c6d26bd576fbdbf" session_cookie="RUUVISESSION" session_id="IZEMZLRSTOBMNMBW"^M
Set-Cookie: RUUVISESSION=IZEMZLRSTOBMNMBW^M

I (111923) http_server: [http_server] Json resp: code=401, content:
{"success": false, "gateway_name": "RuuviGatewayFCC3", "lan_auth_type": "lan_auth_ruuvi"}
I (111938) http_server: [http_server] Respond: 401 Unauthorized
...
I (210203) http_server: [http_server] Request from 192.168.1.49 to 192.168.1.43: POST /auth
I (210205) http_server: [http_server] POST /auth
W (210208) req_post_auth: [http_server] User name in auth_info does not match the username from auth_req
I (210218) http_server: [http_server] Extra HTTP-header resp: WWW-Authenticate: x-ruuvi-interactive realm="RuuviGatewayFCC3"                 +challenge="9c59760e0e262011f38cfc36c88d9d118a74ff724071d401c0a3c7febd3d8682" session_cookie="RUUVISESSION" session_id="AFLNEGTGMQQHFVGU"^M
Set-Cookie: RUUVISESSION=AFLNEGTGMQQHFVGU^M

I (210245) http_server: [http_server] Json resp: code=401, content:
{"success": false, "gateway_name": "RuuviGatewayFCC3", "lan_auth_type": "lan_auth_ruuvi"}
I (210260) http_server: [http_server] Respond: 401 Unauthorized
++++
...
I (273958) http_server: [http_server] Request from 192.168.1.49 to 192.168.1.43: POST /auth
I (273959) http_server: [http_server] POST /auth
W (273963) req_post_auth: [http_server] User name in auth_info does not match the username from auth_req
I (273973) http_server: [http_server] Extra HTTP-header resp: WWW-Authenticate: x-ruuvi-interactive realm="RuuviGatewayFCC3"                 +challenge="645e2ca510fe8f9372562fa8f97ce37b89f94609d0b4dffb80baaf4abe77f7c2" session_cookie="RUUVISESSION" session_id="TNHZPPBLCJETHWBV"^M
Set-Cookie: RUUVISESSION=TNHZPPBLCJETHWBV^M

I (274000) http_server: [http_server] Json resp: code=401, content:
{"success": false, "gateway_name": "RuuviGatewayFCC3", "lan_auth_type": "lan_auth_ruuvi"}
I (274015) http_server: [http_server] Respond: 401 Unauthorized
...
Several more attempts.
W (442166) http_server: [http_server] The connection was closed by the client side ++OK
</pre>

Well let me see how it looks on an iPhone.
Looks better.
<pre>I (442176) http_server: [http_server] Request from 192.168.1.58 to 192.168.1.43: GET /

I (442600) http_server: [http_server] Extra HTTP-header resp: WWW-Authenticate: x-ruuvi-interactive realm="RuuviGatewayFCC3"                 +challenge="753931f4c76c7af0fa49fa1cf97dcf96a3cdfcf27892d99740550745d648940a" session_cookie="RUUVISESSION" session_id="YZRXIIQRBQWQGHHA"^M
Set-Cookie: RUUVISESSION=YZRXIIQRBQWQGHHA^M

I (442625) http_server: [http_server] Json resp: code=401, content:

I (515686) http_server: [http_server] Request from 192.168.1.58 to 192.168.1.43: POST /auth
I (515687) http_server: [http_server] POST /auth
I (515691) http_server: [http_server] Extra HTTP-header resp: Ruuvi-prev-url: /index.html^
Set-Cookie: RUUVI_PREV_URL=; Max-Age=-1; Expires=Thu, 01 Jan 1970 00:00:00 GMT^

I (515706) http_server: [http_server] Json resp: code=200, content:


Wonderful ++++++++++++
I (515713) http_server: [http_server] Respond: 200 OK
I (515753) http_server: [http_server] Request from 192.168.1.58 to 192.168.1.43: GET /index.html
...
I (524023) http_server: [http_server] Request from 192.168.1.58 to 192.168.1.43: GET /status.json
I (524025) http_server: [http_server] Json resp: code=200, content:
{"ssid":null,"ip":"192.168.1.43","netmask":"255.255.255.0","gw":"192.168.1.1","dhcp":"192.168.1.1","urc":0,"lan":1}
</pre>
...

Back to the Mac Book Pro
<pre>
I (582793) http_server: [http_server] Request from 192.168.1.49 to 192.168.1.43: POST /auth
I (582794) http_server: [http_server] POST /auth
W (582797) req_post_auth: [http_server] session_id is empty
I (582803) http_server: [http_server] Extra HTTP-header resp: WWW-Authenticate: x-ruuvi-interactive realm="RuuviGatewayFCC3"                 +challenge="55ba7cb91b317fb7bc35cc1969c1326b1e2a169ce8fe9802e6424f9c9ed0f917" session_cookie="RUUVISESSION" session_id="KKARKPWRELIVRWJT"^M
Set-Cookie: RUUVISESSION=KKARKPWRELIVRWJT^M

I (582830) http_server: [http_server] Json resp: code=401, content:
{"success": false, "gateway_name": "RuuviGatewayFCC3", "lan_auth_type": "lan_auth_ruuvi"}
</pre>++++++++++++++++++++++++++++
back to the iPhone
<pre>
I (1012841) http_server: [http_server] Request from 192.168.1.58 to 192.168.1.43: GET /github_latest_release.json
I (1012842) http: [http_server] http_download
I (1014079) ruuvi_gateway: [main] free heap: 85764
I (1014144) http: [http_server] HTTP_EVENT_ON_CONNECTED

I (1092773) fw_update: [fw_update_task] Write to OTA-partition ota_0, offset 0, size 1371
...
finally
I (1111121) fw_update: [fw_update_task] Write to OTA-partition ota_0, offset 1199764, size 348
I (1111142) http: [fw_update_task] HTTP_EVENT_ON_FINISH
...
I (1127482) fw_update: [fw_update_task] Write to partition fatfs_gwui, offset 0, size 1371
....
I (1146853) fw_update: [fw_update_task] Write to partition fatfs_nrf52, offset 0, size 1371
...
I (1151126) fw_update: [fw_update_task] Write to partition fatfs_nrf52, offset 260239, size 1905
...
I (1157310) fw_update: [fw_update_task] Restart system.  </pre>
YES!!
<pre>
I (680) cpu_start: Project name:     ruuvi_gateway_esp
I (686) cpu_start: App version:      v1.10.0
I (691) cpu_start: Compile time:     Jan 19 2022 16:12:44</pre>
..
