### ISSUE TITLE
Add a local configuration JSON file

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#475]
Continuing #456

**Comment by ojousima** [comment]
This does not need to be an actual "file" on filesystem, it just needs to store the user configuration in flash. 

Requirements: 
 - Has to be downloadable from remote server as JSON
 - Has to survive firmware update
 - Has to be cleared on factory reset

**Comment by TheSomeMan** [comment]
It was implemented in #454
