### ISSUE TITLE
v1.10.1: MQTT over TCP does not work

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#479]
```
E (492549) TRANS_TCP: [sock=54] select() timeout
E (492550) MQTT_CLIENT: Error transport connect
I (492550) MQTT: [mqtt_task] MQTT_EVENT_ERROR
```

**Comment by TheSomeMan** [comment]
@ojousima, it seems that yesterday when I was testing MQTT, the server test.mosquitto.org didn't work well and I had some connection problems. But now it works good and MQTT over TCP works as expected on v1.10.1.
The error message "MQTT_CLIENT: Error transport connect" is printed when the gateway fails to establish connection with MQTT server

**Comment by ojousima** [comment]
Tested and MQTT works on my GW too. Closing.
