### ISSUE TITLE
RSSI drop after update from v1.9.2-> newer

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#488]
Samples:
![image](https://user-images.githubusercontent.com/2360368/154433895-25b53575-00e6-4748-80ca-39c87da54e45.png)
![image](https://user-images.githubusercontent.com/2360368/154433912-7aad8272-6ae5-416c-9147-c0454bfa5f96.png)
![image](https://user-images.githubusercontent.com/2360368/154433938-ca4ffd29-a655-4b57-a784-97fc57df5f27.png)

This is graph of reverting v1.11.0 to v1.9.2:
![image](https://user-images.githubusercontent.com/2360368/154434143-9cf4b359-cdce-4429-b8d6-4498cbb6895d.png)

LNA GPIO control and WiFi coexistence needs to be checked.

**Comment by Scrin** [comment]
Interestingly the amount of received measurements didn't drop at all for me after upgrading from 1.9.2 to 1.10.0 so none of my monitoring alarms caught that, but the RSSI drop is very clear:
![image](https://user-images.githubusercontent.com/6617316/154450705-45b5c2a3-8817-4a2b-91a1-a889af54310f.png)
(the v1.9.2 didn't report the firmware version over /metrics endpoint so that part is blank in the version chart). I guess RSSI monitoring is one more monitoring alarm to add

**Comment by TheSomeMan** [comment]
This happened because the CONFIG_ESP32_WIFI_SW_COEXIST_ENABLE option in sdkconfig disappeared after updating to esp-idf v4.3. And now to enable this option, we need to enable Bluetooth, and then the desired option appears in the configuration menu.

**Comment by ojousima** [comment]
The issue is still present in v1.11.1, update was around 11.00:
![image](https://user-images.githubusercontent.com/2360368/154659333-f269c99e-f8c1-48b1-9528-979fcf058392.png)

**Comment by TheSomeMan** [comment]
It seems that [Wi-Fi Multiple Antennas Configuration](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#wi-fi-multiple-antennas-configuration) has been broken in recent ESP-IDF versions.
See [GPIO for antenna configuration is not working anymore](https://github.com/espressif/esp-idf/issues/6930)
Original discussion: [GPIO for antenna configuration is not working anymore](https://github.com/bisonscience/ESP32-M1-Reach-Out/issues/1)

**Comment by TheSomeMan** [comment]
I tried to build the project with previous esp_idf versions. This feature works in esp_idf v4.2.2, but doesn't work in v4.3 and later versions.

**Comment by TheSomeMan** [comment]
Created separate task: [Downgrade ESP-IDF to v4.2.2](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/493)
