### ISSUE TITLE
Cannot re-enter configuration mode

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#49]
Might be a user error but entering configuration mode is not working.

Make the Gateway to act as a connectable hotspot instantly when user presses ESP's "Configure" button.

**Comment by ojousima** [comment]
This is related to porting hardware from devkits, button is at wrong GPIO

**Comment by ojousima** [comment]
Partially fixed in #51 . Please update the specification at https://docs.ruuvi.com/gw-esp32-firmware/gw-esp32-button to match your expected behavior. Once specifications are agreed on, @TheSomeMan can start working on this.

**Comment by laurijamsa** [comment]
Done. ≤5sec is a short press and >5sec is a long press. Tagging @TheSomeMan

**Comment by ojousima** [comment]
Specification: 
Press < 5 s, restart hotspot
Press > 5 s, "factory reset" and reboot.
https://docs.ruuvi.com/gw-esp32-firmware/gw-esp32-button

**Comment by TheSomeMan** [comment]
whether this task should be performed as part of the milestone 1.2?

**Comment by ojousima** [comment]
@TheSomeMan Yes, I add this to 1.2.

**Comment by TheSomeMan** [comment]
@ojousima after enabling configuration mode, what should be done by next short press? nothing? or disable http server?
Next question - do we need to reset the device to the factory settings by long pressing? because now we're resetting only wifi settings as described in #71.

**Comment by ojousima** [comment]
@TheSomeMan 
>what should be done by next short press?

Several short presses should do nothing, the configuration becomes active on first press and stays active on next presses.

>Next question - do we need to reset the device to the factory settings by long pressing? 

Yes
