### ISSUE TITLE
push button should poke hole v1.11.2 nit

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi.gateway_esp.c#497]
Multiple pages include text:
"...pressing  the small button under the power socket.'

Should say something like:
"... inserting paper clip into small hole under the power socket.
++++++++++++++++++++++

There are also sometimes.  x'ef ac 81' for character 'f' which should be x'66'

 ```
  79 6f 75 20 6d 69 73 63  6f 6e ef ac 81 67 75 72  |you miscon...gur 
  65 64 2c 20 79 6f 75 20  63 61 6e 20 72 65 73 74  |ed, you can rest 
  61 72 74 20 74 68 65 20  63 6f 6e ef ac 81 67 75  |art the con...gu
```

**Comment by laurijamsa** [comment]
Could you please open this issue in the correct repo? Thanks!

https://github.com/ruuvi/ruuvi.gwui.html
