### ISSUE TITLE
Configurable NTP address(es)

### ISSUE THREAD

**Issue by rudam** [ruuvi/ruuvi.gateway_esp.c#499]
Dear Ruuvi team,

I would like to suggest a couple of improvements achieve the ability of the Gateway to operate in the isolated infrastructure, without access to the internet. We, the Czech company Altron I work for, use Gateways and Tags for monitoring the environment in data centres.  Internal technological and sensory networks are mostly and typically fully isolated from the internet. The current version of Gateway firmware depends on the public NTP services. The DHCP NTP option is ignored. It could be more convenient to support DHCP NTP and for manual config of IP the NTP servers configuration options too.

Many thanks and have a nice day.
Michal

**Comment by ojousima** [comment]
Thank you for the feedback. 

@TheSomeMan How much effort this would be to implement? Should it be added to v1.12.0 as we're working on custom installations anyway or should we implement it after v.1.13.0?

**Comment by TheSomeMan** [comment]
implementing configuration support for NTP addresses (or disable them) in UI can be done quite quickly, within a couple of days, so I think it can be added to v1.12.0.

As for the DHCP NTP option support I'd suggest implementing in the next version.

**Comment by ojousima** [comment]
I have split this task in 2 parts: First we add configurable NTP addresses. In second part we add DHCP support.

First part should be ready by May for v1.12.0 release, second part in May-June for v1.13.0 release. @rudam FYI

**Comment by TheSomeMan** [comment]
How to test:
1. On the Cloud options page open Advanced settings and select using a custom server
2. On the Time Synchronization Options page select using a custom set of NTP servers
3. Enter 1-2 different NTP servers and leave other fields empty (try empty first NTP server)
4. Save configuration, reboot the gateway, check that time was synchronized and data are relayed to HTTP (or MQTT)

**Comment by markoaamunkajo** [comment]
QA passed
