### ISSUE TITLE
Implement support for DHCP-NTP 

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#500]
Step 2 of https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/499

**Comment by DG12** [comment]
Any chance to include 
DHCP option 7 logging server while you are at it?

**Comment by TheSomeMan** [comment]
This task was closed as part of #499 / #508

**Comment by TheSomeMan** [comment]
How to test:
1. Configure your DHCP server - enable ntp-servers option and specify a list of IP addresses
2. Configure Gateway to use DHCP to get a set of NTP servers
3. Check that Gateway reconnected to the network and got new NTP servers (by syslogs), check that time was synchronized
4. Reboot Gateway and check that the list of NTP servers was received from DHCP and time was synchronized

**Comment by ojousima** [comment]
I don't have access to a router that would support DHCP-NTP options right now, @rudam can you give it a try? 

You'd need to update the firmware to v1.12.1 prerelease if you test it out.

**Comment by rudam** [comment]
Dear friends.
I am so sorry for the delay with my comment here. We extensively tested these newly implemented features, and I want to say THANK YOU! Everything works as we needed. I appreciate it so much.
Michal
