### ISSUE TITLE
Add instructions for verifying build

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#501]
Users should be able to check their firmware against automated builds, similar to https://core.telegram.org/reproducible-builds

**Comment by TheSomeMan** [comment]
[reproducible builds for ESP32 ](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/reproducible-builds.html)

**Comment by TheSomeMan** [comment]
It seems that it's impossible to create a reproducible build for the bootloader without patching ESP-IDF.
Need to modify ESP_IDF/components/bootloader/subproject/CMakeLists.txt and add the following lines after 'project(bootloader)' declaration:
```
idf_build_set_property(COMPILE_OPTIONS "-ffile-prefix-map=${CMAKE_SOURCE_DIR}=." APPEND)
idf_build_set_property(COMPILE_OPTIONS "-ffile-prefix-map=$ENV{IDF_PATH}=IDF" APPEND)
idf_build_set_property(COMPILE_DEFINITIONS "-D__TIME__=\"\"" APPEND)
idf_build_set_property(COMPILE_DEFINITIONS "-D__DATE__=\"\"" APPEND)
```
