### ISSUE TITLE
Uptime rarely exceeds a week

### ISSUE THREAD

**Issue by Scrin** [ruuvi/ruuvi.gateway_esp.c#507]
It seems like the gateway reboots on its own every now and then, sometimes the uptime barely reaches a day, sometimes it goes nicely for a few weeks even, and there doesn't seem to be any pattern.

See this uptime graph:
![image](https://user-images.githubusercontent.com/6617316/165084896-3b8eaa61-30ea-441f-ad12-dc1d70bcf61c.png)
(live graph including fw versions etc: https://graphs.2kgwf.fi/d/IY4bSTIGz/ruuvi-gateway ).

The power supply is stable so that's not the cause (I've tried swapping the supply with other similar devices and no change), any idea what might cause these random reboots?

I suppose the logs could tell something, but given this is still relatively rare occurrence and the location of my gateway makes it wildly inconvenient to get logs from when this happens, at least without remote logging support (ie. #230)

**Comment by ojousima** [comment]
This might have been solved in #520, I'll see how the uptime looks like on release candidate

**Comment by TheSomeMan** [comment]
This should be fixed in #509 or #519 (we don't know the exact reason for this problem)

**Comment by ojousima** [comment]
I don't have a Gateway that would be on for a long period, they get reset when I try out issues. 

We have uptime monitoring of Gateways, let's see how it goes once next release is rolled out and reopen if necessary
