### ISSUE TITLE
Replace fatfs partition for default configuration storage with NVS partition

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#515]

**Comment by DG12** [comment]
What prompted  this?

**Comment by TheSomeMan** [comment]
> What prompted this?

Creating fatfs partition requires building of a third party utility "mkfatfs", 
while creation of NVS partition can be done using the utility "nvs_partition_gen.py", which is part of ESP-IDF.
We only support building "mkfatfs" on Linux, so Windows/MacOS users may find it more difficult to create this partition.

**Comment by TheSomeMan** [comment]
The test procedure is the same as for #454
