### ISSUE TITLE
UI: Hide "Time Synchronization Options" under "Cloud options / Advanced Settings"

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#523]

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
1.12.1. I read the title wrong about hiding "from" instead of hiding "under" at first.

Looks like Time Synchronization Options don't exist under Cloud Options/ Advanced Settings.
