### ISSUE TITLE
Integration with AWS IoT: Store CA's on Gateway so it could connect directly to AWS IoT Core

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#528]
X.509 client certificate + CA support would be best option

**Comment by ojousima** [comment]
Is this a duplicate of #476

**Comment by laurijamsa** [comment]
> Is this a duplicate of #476?

@TheSomeMan can we close this?

**Comment by laurijamsa** [comment]
This is a duplicate of #476, closing.
