### ISSUE TITLE
Hotspot: Windows 10 continually redirects browser.

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#53]
Windows 10 machine redirects browser to http://www.msftconnecttest.com/redirect, which doesn't redirect to 10.10.0.1. 
Possible solution: https://lemariva.com/blog/rss/white-hacking-wemos-captive-portal-using-micropython

Reporter Henri.

**Comment by TheSomeMan** [comment]
I think this issue is related to #34, and it does not manifest itself in the latest firmware.

**Comment by ojousima** [comment]
Ok, I'll check if this issue still occurs with build of https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/53/

**Comment by ojousima** [comment]
This issue is not anymore blocking. The Windows machine is redirected to http://www.msftconnecttest.com/redirect but it automatically redirects to 10.10.0.1. Closing.
