### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#533]

**Comment by TheSomeMan** [comment]
https://docs.ruuvi.com/ruuvi-gateway-firmware/gw-getting-started

**Comment by markoaamunkajo** [comment]
Sent review back to include mention about latest footer statuses in advanced guide

**Comment by TheSomeMan** [comment]
> Sent review back to include mention about latest footer statuses in advanced guide

I've updated the advanced guide, see my pull request here: https://github.com/ruuvi/ruuvi.gateway_esp.c/pull/690

**Comment by markoaamunkajo** [comment]
Review approved, assigning back to @TheSomeMan

**Comment by markoaamunkajo** [comment]
Links changed in documentation, moving to done
