### ISSUE TITLE
v1.12.1: Static Ethernet IP address fails unless all fields are given

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#544]
Configuring only static IP address, Gateway address, subnet mask and leaving DNS addresses blank leads to Gateway failing DNS queries and rebooting.

Steps to repeat: Configure Static Ethernet IP address, leave DNS addresses blank. 

My expectation would be that blank DNS addresses would be fetched via DHCP. Marking this as an usability issue for v1.13.0

<img width="725" alt="image" src="https://user-images.githubusercontent.com/2360368/174661738-7ce7816f-36e6-4aa5-9b25-ca483c16a6d3.png">

**Comment by markoaamunkajo** [comment]
QA passed
