### ISSUE TITLE
Memory leak when saving configuration (v1.12.1)

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#548]
Description:

I was testing different configurations between Ruuvi Cloud and MQTT, spotted this in the logs.

E (1455355) ruuvi_gateway: [main] /Users/otsojousimaa/git/ruuvi.gateway_esp.c/main/main_loop.c:170 {main_task_handle_sig_log_heap_usage}: Only 1KiB of free memory left - probably due to a memory leak. Reboot the Gateway.

[memory_leak.txt](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/8957623/memory_leak.txt)

**Comment by ojousima** [comment]
@TheSomeMan Is this ready for review by @markoaamunkajo?

**Comment by TheSomeMan** [comment]
> @TheSomeMan Is this ready for review by @markoaamunkajo?

yes, it's ready. sorry, I forgot to reassign it

**Comment by markoaamunkajo** [comment]
QA passed
