### ISSUE TITLE
UI: Make a dropdown list with language selection in the top right corner

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#549]

**Comment by TheSomeMan** [comment]
[link](https://github.com/ruuvi/ruuvi.gwui.html/issues/202)

**Comment by laurijamsa** [comment]
Overlapping on my mobile browser. Works otherwise ok:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/1311912/175946635-f7d26cc3-25b3-4d96-9ad8-a9c5b2eed58a.png">

**Comment by TheSomeMan** [comment]
![image](https://user-images.githubusercontent.com/4346875/176985135-9487a7a1-019b-4280-98dc-ace73c3090cf.png)
