### ISSUE TITLE
Log gets filled with no network connection messages

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#590]
Description:

User configured test.mosquitto.net with wrong settings to Ruuvi configurator and saved.
Now logs are full of entries for no network connection

Solution:
Print once per minute, just to see that MQTT is being used

**Comment by markoaamunkajo** [comment]
https://user-images.githubusercontent.com/50437378/180013785-dab1ded8-5a35-4c99-8c73-d6c2079c75f7.mov

**Comment by ojousima** [comment]
Fixed in v1.12.1-34-g0b75633, marking as done
