### ISSUE TITLE
Turn off DNS server as soon as it is no longer needed

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#602]

**Comment by dgcccu** [comment]
Does this prevent observing changes to DNS database i.e. old hostname.IP to hostname:NEW_IP

**Comment by TheSomeMan** [comment]
> Does this prevent observing changes to DNS database i.e. old hostname.IP to hostname:NEW_IP

Sorry, I don't quite understand what you mean.
DNS server is activated on the Gateway after WiFi hotspot is started in order to redirect from any hostname to fixed IP 10.10.0.1.
After Web configurator is loaded to the browser, DNS server is no longer needed. Leaving it running is not good because firstly, it takes memory, and secondly, with a large flow of DNS requests from the client computer, it slows down other threads.

**Comment by DG12** [comment]
Thanks for the explanation
"...redirect from any hostname to fixed IP 10.10.0.1..."

Will a connection from a new browser from a new client still resolve correctly?

**Comment by TheSomeMan** [comment]
> Will a connection from a new browser from a new client still resolve correctly?

If you start a new browser and enter IP manually, then you don't need DNS server on the Gateway.
DNS server is only needed for the captive portal - when a client connects to Gateway's hotspot, requests to any website are redirected to 10.10.0.1, and OS automatically opens a browser window with Gateway's captive portal.

**Comment by markoaamunkajo** [comment]
QA passed
