### ISSUE TITLE
UI: Connection with Gateway is lost after going back from WiFi Network page and forth; sometimes 'loading' icon is hidden prematurely

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#607]
[Sometimes connection with Gateway is lost after returning back from WiFi Network page and returning to this page again](https://github.com/ruuvi/ruuvi.gwui.html/issues/231)
[Sometimes 'loading' icon hides before actual connecting to WiFi](https://github.com/ruuvi/ruuvi.gwui.html/issues/227)

**Comment by markoaamunkajo** [comment]
QA passed
