### ISSUE TITLE
WiFi hotspot does not start after erasing all flash memory

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#614]

**Comment by laurijamsa** [comment]
reopening. hotspot activation should be disabled after auto-configuring

**Comment by laurijamsa** [comment]
tested the build 697 but still access point is started even if my ethernet is connected (but internet is not available as it's currently broken)

Log:
[697.log](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/9426955/697.log)

**Comment by TheSomeMan** [comment]
> tested the build 697 but still access point is started even if my ethernet is connected (but internet is not available as it's currently broken)
> 
> Log: [697.log](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/9426955/697.log)

Yes, but Wi-Fi hotspot is started only once after erasing configuration. After a network connection is established (Ethernet or Wi-Fi), hotspot activation is disabled, so on the next reboot hotspot will not start

**Comment by laurijamsa** [comment]
Reopening. We decided in the chat that:

"hotspot will start if configuration is cleared by the long pressing on the configure button even if ethernet cable would be connected. but if configuration is cleared with esptool, then we first check if Ethernet is connected. If not connected, then start hotspot"

**Comment by laurijamsa** [comment]
I think this is fine. Moving to done.
