### ISSUE TITLE
Check if the configuration button is pressed at the earliest stage after rebooting

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#621]
The state of the button is currently checked 3 seconds after a reboot, and if the user accidentally presses the button at this point, the gateway configuration will be erased. 
In addition, the user must press and hold the button for at least 5+3=8 seconds to clear the gateway configuration.

**Comment by markoaamunkajo** [comment]
QA passed 1.12.-60-gf4ed33a
