### ISSUE TITLE
Make configuration hotspot name more intuitive

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#626]
An idea: What about if we would rename the hotspot to:

**Configure Ruuvi Gateway XXXX**

That would make it even more clear to users that what the hotspot is for. Max network name is 32 charachers and this would be 28

**Comment by TheSomeMan** [comment]
WiFi AP name now takes up two lines:
![image](https://user-images.githubusercontent.com/4346875/201827699-90fc3114-23f4-4ebd-a689-8dd5a971f461.png)

**Comment by laurijamsa** [comment]
Should be fine because the first 2 words are the most important ones and if in some rare situations user's device shortens long network namesm "Configure Ruuvi" will be shown anyways.
