### ISSUE TITLE
UI: Ethernet error message is shown on top of other texts and it looks messy

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#628]
![telegram-cloud-photo-size-5-6087081871461693107-y](https://user-images.githubusercontent.com/1311912/187639879-305ebc12-54ac-403f-95b1-26ff10e24179.jpg)

build 708

**Comment by TheSomeMan** [comment]
![image](https://user-images.githubusercontent.com/4346875/201835601-dedf614b-ef2e-4caf-9c35-c00da45b48bd.png)

**Comment by markoaamunkajo** [comment]
QA passed
