### ISSUE TITLE
Confusing behavior when supplying a Bearer token without enabling authentication

### ISSUE THREAD

**Issue by Scrin** [ruuvi/ruuvi.gateway_esp.c#630]
It seems that if one does not enable authentication on the gateway and then tries to poll the /history endpoint for example with any Bearer authentication, the gateway rejects the call with http error 401. I would expect the gateway to completely ignore the Authorization header if authentication is not enabled.

Steps to reproduce:
- Configure a gateway with no authentication (use the "Remote configurable without a password (unsafe, not recommended)" option in Access Settings page)
- Try to call the /history endpoint with `curl -v gateway.ip.address/history` and notice it's working as expected
- Try to call the /history endpoint with `curl -vH"Authorization: Bearer foo" gateway.ip.address/history` and notice the gateway returning a http 401 error back, even though authentication should be disabled

**Comment by TheSomeMan** [comment]
Tested it with v1.12.4, and it works as expected.
I set access settings to "No remote configurable", enabled the use of bearer token and set it to "foo":

* Error 403 (Forbidden) is returned on `curl -v gateway.ip.address/history` 
* Good response (200 OK) is returned on `curl -vH"Authorization: Bearer foo" gateway.ip.address/history` 
* Error 401 (Unauthorized) is returned on `curl -vH"Authorization: Bearer wrong_token" gateway.ip.address/history` 

@Scrin could you please re-test? maybe you used an incorrect bearer token?

**Comment by Scrin** [comment]
This issue is about when authentication should be **disabled**, that is, using the **"Remote configurable without a password (unsafe, not recommended)"** option in Access Settings page (as mentioned in the "steps to reproduce"). If I enable authentication, then everything works as expected indeed. If I **disable authentication** I would expect the gateway to ignore any Authorization headers, as they serve no purpose without authentication

**Comment by TheSomeMan** [comment]
I think it's more a question of documentation and user interface.
This bearer token is supposed to be used for gateway operation in polling mode (see [polling-mode](https://docs.ruuvi.com/gw-examples/polling-mode)), so it is used only for read-only access to "/history" and "/metrics" endpoints. But regular authentication additionally allows read and write access to the gateway configuration.

**Comment by Scrin** [comment]
Well, either case the current behavior is confusing / not consistent:

- If the /history and /metrics endpoints are supposed to be accessible without a token if authentication is disabled (like it works right now), the gateway should not reject calls that happen to have an Authorization header present while letting calls without the header through
- If the /history and /metrics endpoints are supposed to require the use of a bearer token at all times, then there is currently a bug that allows access to these endpoints without a token if authentication is disabled

If I understand you correctly, I believe it's the 2nd case that applies here.

Personally I would expect the 1st case to apply here since a token doesn't add anything to the security if the gateway is configured to be configurable without any credentials, but that's not my decision to make

**Comment by TheSomeMan** [comment]
I propose to change UI as follows:
![image](https://user-images.githubusercontent.com/4346875/194063053-0866cf05-bf63-4180-8d6b-dabd157e7c52.png)

@ojousima what do you think?

**Comment by ojousima** [comment]
The UI change is good in my opinion. 

To summarize:
* When remote configuration has open access /history and metrics should always be allowed to read. Even if there is read-only token with invalid or empty value, security check should be skipped
* When remote configuration is enabled with authentication, /history and metrics should be viewable either in browser with correct authentication or with valid read-only token
* When remote configuration is forbidden, valid read-only token should still work

**Comment by TheSomeMan** [comment]
> Personally I would expect the 1st case to apply here since a token doesn't add anything to the security if the gateway is configured to be configurable without any credentials

@Scrin Right, if the gateway is configured to be configurable without any credentials, then users don't care about security and they don't need to use a bearer token. Perhaps, we need to disable it in UI: when set to "Remote configurable without a password", it should not be possible to enable the use of a bearer token. What do you think, @ojousima?

But when access to the configuration of the gateway is restricted, then we can use a bearer token for read-only access to "/history" via LAN.
You might wonder why we need an additional authentication mechanism. Well, let me explain. When the access settings are configured to "Password protected with the default password" or "Protected with a custom password", then it's not so easy to get access to the gateway using simple tools like `curl`. When using regular authentication, a unique session cookie must be passed in the request to access the gateway. This cookie is generated by the gateway in response to the authentication request. And this authentication request requires two steps. First, request the gateway name and some random value from the gateway. Second, generate a hash from the username, password, gateway name and the passed random value. This hash is used for authentication and the gateway returns the session cookie.
For those users who want to collect data from the gateway in polling mode, such authentication is too complicated and they can configure the gateway for read-only access to "/history" using a bearer token.

**Comment by ojousima** [comment]
> Perhaps, we need to disable it in UI: when set to "Remote configurable without a password", it should not be possible to enable the use of a bearer token. What do you think, @ojousima?

That would be more clear signal for the user that the bearer token adds nothing for the security when passwordless access is allowed.
