### ISSUE TITLE
Documentation: Check nRF52 <-> ESP32 UART communication

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#639]
https://docs.ruuvi.com/ruuvi-gateway-firmware/gw-nrf52-firmware/gw-nrf52811-uart-communication

**Comment by TheSomeMan** [comment]
@ojousima could you please review https://docs.ruuvi.com/ruuvi-gateway-firmware/gw-nrf52-firmware/gw-nrf52811-uart-communication ?

**Comment by DG12** [comment]
A) Adding a description above 'message format' would be nice.

B) Which is host/device ?

C) Perhaps you could omit the  [STX].  and [CRC16][ETX] from table /box descriptions. That would reduce heading text wrap.

D) Maybe a note that LEN of 00 indicates 1 byte on payload

E) Great "Complete message" details !

F1) "Example of a command to set the state of channel 37" could be 
Set the state of channel 37
F2) "<s>Example of a command to </s>set all configuration
F...) "<s>Example of </s>GET DEVICE_ID <s>sequence</s>
"Report payload <s>format </s>

G) ACK payload format  seems to be arranged vertically where others are horizontally
i.e.  Ack has rows describing bytes, others use columns.
Same issue with "request/response payload format"

G1) ACK payload format might better be "ACK message" an dinclude STX + LEN , CRC ETX .
Then description of other commands need not include "Ack RE_CA_UART_ACK:" details.

G2)  In ACK message, is "CMD" the command that the ACK is responding to ? If so add that.

H) Are "Num" 00, 01, 02, 03, 04 used ?

I) Report payload format  <b>How is end of Adv determined? </b>

J) Do "Num" and "CMD" both refer to the command_code ?


Hope this helps.

**Comment by ojousima** [comment]
Thanks @TheSomeMan , looks good.

@DG12 This is mostly for internal record-keeping, we don't practically expect users to eavesdrop between the chips. Of course the documentation can always be improved, but those efforts are focused on user-facing APIs for now. This update fixed some mistakes in documentation.

**Comment by DG12** [comment]
I am mostly interested in
I) Report payload format How is end of Adv determined?

as most of my other comments address cosmetic rather than content issues.

**Comment by ojousima** [comment]
> I) Report payload format How is end of Adv determined?

The end is determined with the length byte and sanity checked with the delimiter byte.

**Comment by TheSomeMan** [comment]
@DG12 thank you for your suggestions.
@ojousima I started improving the documentation yesterday and have already finished. Please check it.

**Comment by DG12** [comment]
Thank you for you considerations.

Looks great no.

One final suggestion

at very top
Lifecycle: Beta. Last updated 2021-04-15

**Comment by TheSomeMan** [comment]
> at very top
> Lifecycle: Beta. Last updated 2021-04-15

Thanks, fixed
