### ISSUE TITLE
Add a write-bearer for configuring the Gateway with a bearer token

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#640]
e.g. `curl -d @config.json -H "Authorization: Bearer <TOKEN>" http://192.168.1.100` and a sample of config JSON. Please note I haven't checked the curl syntax here

**Comment by TheSomeMan** [comment]
Currently, we don't allow to read/write configuration using Bearer token. It is used only for "/history" and "/metrics" endpoints

**Comment by TheSomeMan** [comment]
@ojousima here is an extract from the Gateway configuration guide for advanced users:

If you set a token for read-only access, you can read data from the "/history" and 
"/metrics" endpoints, or read the gateway configuration. To be able to configure the gateway 
programmatically, a full (read/write) access token must be enabled.

Examples:
* Request "/history" using read-only bearer token:
```
    curl -v http://<RUUVI_GW_IP>/history 
      -H "Authorization: Bearer Uj+4tj24unVekco/lTLTRyxUfv1J8M6U+sbNsKTWRr0="
```
* Request "/metrics" using read-only bearer token:
```
    curl -v http://<RUUVI_GW_IP>/metrics 
      -H "Authorization: Bearer Uj+4tj24unVekco/lTLTRyxUfv1J8M6U+sbNsKTWRr0="
```
* Download the gateway configuration using the read-only access bearer token and save it to file 
  'ruuvi.json':
```
    curl -v http://<RUUVI_GW_IP>/ruuvi.json 
      -H "Authorization: Bearer Uj+4tj24unVekco/lTLTRyxUfv1J8M6U+sbNsKTWRr0=" 
      --output ruuvi.json
```
* Upload the gateway configuration using the read-write access bearer token 
  from the file './ruuvi.json' (note that the network part of the configuration will be ignored):
```shell
    curl -v http://<RUUVI_GW_IP>/ruuvi.json 
      -H "Authorization: Bearer 1SDrQH1FkH+pON0GsSjt2gYeMSP02uYqfuu7LWdaBvY=" 
      -d @./ruuvi.json 
```
* Starting firmware update from URL:
```
    curl -v http://<RUUVI_GW_IP>/fw_update.json 
      -H "Authorization: Bearer 1SDrQH1FkH+pON0GsSjt2gYeMSP02uYqfuu7LWdaBvY=" 
      -H 'Content-Type: application/json' 
      -d '{"url":"https://my_server.com:7000/gw_firmware/"}'
```
* A forced download of gateway configuration from the remote server (you must pre-configure the 
  gateway and set the remote server URL):
```
    curl -v http://<RUUVI_GW_IP>/gw_cfg_download 
      -H "Authorization: Bearer 1SDrQH1FkH+pON0GsSjt2gYeMSP02uYqfuu7LWdaBvY=" -d ''
```
