### ISSUE TITLE
Add "show password" icon to all password fields

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#642]

**Comment by sini-maaria** [comment]
Icons
[icons.zip](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/9979343/icons.zip)

**Comment by markoaamunkajo** [comment]
@TheSomeMan let's replace the eye icons with these more funky ones

**Comment by markoaamunkajo** [comment]
QA passed
