### ISSUE TITLE
Remote access password does not allow to login

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#677]
Description:

v1.12.4-43-g18936ae

Added new details to Access Settings page

original: - Remote configurable without pw
new: - Protected with a custom pw (edited username and pw fields)

Continued to finish configuration, then accessed config page on another device through browser.

Actual: error: incorrect username or password
Expected: new password saved

**Comment by markoaamunkajo** [comment]
I also tried changing username and I see it in logs correctly, just pw is not saving for me.

[custom_login_incorrect_username_pw.txt](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/10191371/custom_login_incorrect_username_pw.txt)

**Comment by TheSomeMan** [comment]
This bug appeared after implementing #626, because the password is saved after hashing along with the name of WiFi AP.

**Comment by markoaamunkajo** [comment]
QA passed
