### ISSUE TITLE
Change FW update to a custom server

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#685]

**Comment by ojousima** [comment]
Investigate firmware signing while implementing this

**Comment by ojousima** [comment]
Also, automatic update URL should be configurable as a part of this task

**Comment by laurijamsa** [comment]
We decided in the meeting that best way would be to do this redirecting on Ruuvi Cloud server side.

**Comment by markoaamunkajo** [comment]
Remind Otso to ask from Cloudvisor

**Comment by ojousima** [comment]
- Needs a JSON-file download. 
 * Initially static, in the future it could be generated on the fly for slow roll out
- Also needs a directory with binaries

e.g. 
`network.ruuvi.com/firmware-update/latest.json` <- return latest production FW directory
`network.ruuvi.com/firmware-update/beta.json` <- return latest beta FW directory
`network.ruuvi.com/firmware-update/alpha.json` <- return latest development build

and directories
`network.ruuvi.com/firmware-update/v1_13_1/FILE` <- return v1.13.1 file in directory

**Comment by ojousima** [comment]
@TheSomeMan please check https://testnet.ruuvi.com/firmwareupdate, right now the output is 
```
{
  "tag_name":"v1.13.1",
  "download_url":"https://network.ruuvi.com/firmwareupdate/v1.13.1",
  "created_at":1688649523698
}
```
And files would be e.g. `https://network.ruuvi.com/firmwareupdate/v1.13.1/fatfs_gwui.bin`

Your thoughts?

**Comment by TheSomeMan** [comment]
@ojousima could you change the attribute name "created_at" to "published_at" and set the actual value for it "2023-03-15T15:18:54Z"?
And as I see, there are no files in https://network.ruuvi.com/firmwareupdate/v1.13.1/. Can you add binaries so that I can test the updating procedure?

**Comment by ojousima** [comment]
@danagy1 let's change the timestamp format to above ^.

@TheSomeMan we're figuring the files out, I'll ping you once they can be downloaded

**Comment by markoaamunkajo** [comment]
QA passed
