### ISSUE TITLE
Improve WiFi hotspot activation logic after after resetting the gateway settings

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#691]
- First reboot after erasing settings
** Ethernet cable connected:
    Activate hotspot after reboot, init Ethernet after 1 minute. The default configuration will be set and the hotspot will be stopped
** Ethernet cable not connected:
    Activate hotspot after reboot, init Ethernet after 1 minute. Hotspot will be active until Ethernet cable is connected. After 1 hour gateway will be restarted by network timeout

- Subsequent reboots
** Ethernet cable connected:
    Activate hotspot and init Ethernet after reboot. The default configuration will be set and the hotspot will be stopped.
** Ethernet cable not connected:
    Activate hotspot and init Ethernet after reboot. Hotspot will be stopped after 1 minute if there is no client connection to the hotspot. If Ethernet is connected, then the default configuration will be set.

**Comment by markoaamunkajo** [comment]
@TheSomeMan for me in testing the wifi disappeared from available wifi networks in about 30 minutes, not 1 hour.
Can this be correct?

**Comment by TheSomeMan** [comment]
> @TheSomeMan for me in testing the wifi disappeared from available wifi networks in about 30 minutes, not 1 hour. Can this be correct?

No, that's not correct. Has the Gateway rebooted? Do you have any logs?

**Comment by markoaamunkajo** [comment]
I updated fw using fw url in configurator, update was successful, then I visited hotspot once to see that it opens, then closed it and waited to see how long hotspot says on. Ethernet cable not connected.

Is this the correct way to test this?


[loki 2.txt](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/10799474/loki.2.txt)

**Comment by TheSomeMan** [comment]
> I updated fw using fw url in configurator, update was successful, then I visited hotspot once to see that it opens, then closed it and waited to see how long hotspot says on. Ethernet cable not connected.
> 
> Is this the correct way to test this?

No, this is not the right way to test. Your gateway already had some configuration, so after you disconnected from the AP, the Gateway stopped the AP after one minute and connected to the configured WiFi network.
WiFi hotspot will only be active for one hour only after the full configuration erase (by long pressing the Configure button).

**Comment by markoaamunkajo** [comment]
** Ethernet cable not connected:
Activate hotspot after reboot, init Ethernet after 1 minute. Hotspot will be active until Ethernet cable is connected. After 1 hour gateway will be restarted by network timeout

I saw the timeout and light turned green in gateway. What I'm seeing is that I can continue connecting and disconnecting from gateway as much as I like and there is no 1 minute stop on hotspot. Nothing was added to the logs after initial restart of the system.

Is this expected?

**Comment by TheSomeMan** [comment]
> What I'm seeing is that I can continue connecting and disconnecting from gateway as much as I like and there is no 1 minute stop on hotspot. 

Correct, as long as the gateway is not configured, the 1-minute timeout to stop AP is inactive.

> At about 1h 8 minutes this happened and hotspot is no longer available:

After one hour the network watchdog was triggered and Gateway was rebooted. On the second (and subsequent) reboots after the configuration has been erased, the WiFi AP only starts for one minute after the reboot.
Red flashing LED means that there is no network connection.

**Comment by markoaamunkajo** [comment]
QA passed.
