### ISSUE TITLE
Hostname sent via DHCP option 12 contains invalid spaces

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#696]

**Comment by markoaamunkajo** [comment]
Connect to router
Usually router allows to see device names
If you see valid name, ruuvi gateway
Compare previous builds with last build

Previous build would probably show no name at all, new build should show

**Comment by markoaamunkajo** [comment]
Spotted in router DHCP clients list, QA passed
