### ISSUE TITLE
UI: Validation check for time servers

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#697]

**Comment by ojousima** [comment]
How much effort implementing this is?

**Comment by TheSomeMan** [comment]
> How much effort implementing this is?

In the worst case, it will require porting some functions from LWIP/sntp.c and implementing custom interaction with the time servers - this could take about a week. In the best case scenario, it may be possible to get the synchronisation status for each server, then it will take a couple of days.

**Comment by ojousima** [comment]
Thanks, let's check the level of effort needed before starting implementation

**Comment by markoaamunkajo** [comment]
Moving to done
