### ISSUE TITLE
Implement Link-Local Multicast Name Resolution (LLMNR) to resolve the Gateway hostname

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#700]
[Link-Local_Multicast_Name_Resolution](https://en.wikipedia.org/wiki/Link-Local_Multicast_Name_Resolution)
[LLMNR in FreeRTOS](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/LLMNR.html)
[Example LLMNR for ESP8266](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266LLMNR)

**Comment by markoaamunkajo** [comment]
"As of April 2022, Microsoft has begun the process of phasing out both LLMNR and [NetBIOS] name resolution in favour of [mDNS](https://en.wikipedia.org/wiki/Multicast_DNS"

**Comment by TheSomeMan** [comment]
> "As of April 2022, Microsoft has begun the process of phasing out both LLMNR and [NetBIOS] name resolution in favour of [mDNS](https://en.wikipedia.org/wiki/Multicast_DNS"
> 
> @TheSomeMan would this invalidate this task, it looks like mDNS is zero configuration.

Yes, I think we can close this task.
