### ISSUE TITLE
GATT sync ending up with one measurement in the future

### ISSUE THREAD

**Issue by priyonto** [ruuvi/ruuvi.gateway_esp.c#706]
One iOS user reported this issue and this is only happening for one particular tag. Here are the files from the user. 
The last measurement was from the future. 

[Ruuvi 7472_20230226-1348.csv](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/10912866/Ruuvi.7472_20230226-1348.csv)
[Ruuvi 7472_20230226-1404.csv](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/10912867/Ruuvi.7472_20230226-1404.csv)
[Ruuvi D0AD_20230226-1349.csv](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/10912868/Ruuvi.D0AD_20230226-1349.csv)

**Comment by ojousima** [comment]
Is this about BLE/GATT sync or about Cloud sync?

**Comment by priyonto** [comment]
Gatt

**Comment by ojousima** [comment]
GATT sync is not related to the Gateway, closing
