### ISSUE TITLE
Use bootloader and partition_table from v1.9.2 

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#715]

**Comment by TheSomeMan** [comment]
@ojousima could you please attach the bootloader.bin, partition-table.bin and ota_data_initial.bin used in production?

**Comment by ojousima** [comment]
GitHub does not support .bin attachments, so zipped the. They are same files as in v1.9.2 release, verified with shasum:
`shasum bootloader.bin 
1f47b97997f74c503a8edbd2ca78fdbe035a83ad  bootloader.bin`
`shasum partition-table.bin 
32b09d5338c63f7b2416c6d2eaa3eb65cb6ce816  partition-table.bin`
`shasum ota_data_initial.bin 
5e2b96c19c4f5c63a5afa2de504d29fe64a4c908  ota_data_initial.bin`
[binaries.zip](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/10955266/binaries.zip)
