### ISSUE TITLE
UI: Mobile layout: styling fixes

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#718]
Description:

On mobile configuration page has language selector placed too high.
Add some padding to the top of the page to make it look less cramped on mobile screen.

![padding_top](https://user-images.githubusercontent.com/50437378/224873571-3f72caaf-2608-49bd-8835-fd0aef94b914.jpg)

Also please fix the URL and version numbers as follows on both mobile and desktop:

- Version number smaller font
- URL slightly closer to Ruuvi logo

<img width="458" alt="URL-version-number" src="https://user-images.githubusercontent.com/50437378/224877587-35bc3a2d-18ef-4e47-9939-195dc8a873c6.png">

**Comment by markoaamunkajo** [comment]
@TheSomeMan I still see same size font in build version comparing to ruuvi.com. Let's fix this in the next release.
 
![font_smaller](https://user-images.githubusercontent.com/50437378/226818713-7362f68a-2226-4acb-a857-e1e135c60bb4.jpg)

**Comment by TheSomeMan** [comment]
@markoaamunkajo What platform do you use? iPhone/Android? Which browser?

**Comment by markoaamunkajo** [comment]
@TheSomeMan iPhone 14 Pro, Chrome browser

**Comment by markoaamunkajo** [comment]
QA passed
