### ISSUE TITLE
UI: Fix font styles and text alignment

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#719]
Description:

Looks like text formatting is inconsistent on some pages.
Please check that on every page:

- Text is aligned to left. NOT justified.
- Text font and style is consistent in body. Text is plain text without bold or any formatting added.

![justify-font-style2](https://user-images.githubusercontent.com/50437378/224875800-3c8995e6-ff26-45d3-8d3c-4c9571e5c0b3.jpg)
![justify-font-style](https://user-images.githubusercontent.com/50437378/224875804-82b5894f-8a62-4478-92d1-ed1473a5a932.jpg)

**Comment by TheSomeMan** [comment]
As for the "Software update page", I can align firmware version info to the left:
![image](https://user-images.githubusercontent.com/4346875/224894422-b5439ae1-b80d-492d-8d11-fe336600a174.png)
But the text "An update is available! Press UPDATE to start the firmware update." is not regular text on the page - it's a message with a firmware update checking status.
There are two other possible messages:
![image](https://user-images.githubusercontent.com/4346875/224894670-c242873f-1c9b-41fd-8e5b-1fdbdc914e38.png)
![image](https://user-images.githubusercontent.com/4346875/224894691-6612d56b-4dde-4785-bfd3-b62ffeb2a208.png)

@laurijamsa, @markoaamunkajo could you review and choose a style for these messages?

**Comment by markoaamunkajo** [comment]
QA passed for EN

Will open separate card to add same fixes for FI in the next release

**Comment by TheSomeMan** [comment]
@markoaamunkajo it seems that this issue was mistakenly moved to InProgress, could you check that all related problems have been fixed in the last build?

**Comment by markoaamunkajo** [comment]
Commented in dm, waiting for new build.

**Comment by markoaamunkajo** [comment]
@TheSomeMan there is an alignment issue in FI language

![Image](https://user-images.githubusercontent.com/50437378/235813850-92ec2790-760b-4447-8362-3b0f1949af2f.jpeg)

**Comment by markoaamunkajo** [comment]
QA passed
