### ISSUE TITLE
resetting the configuration by pressing the reset button does not work if the gateway reboots in first 5 seconds

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#72]
In case when the gateway restarts due to bad configuration there is no way to reset gateway settings.
I suggest following solution:
1. Pressing the reset button for 5 seconds will reboot the device (without clearing the configuration)
2. On the first stage of the boot check if the reset button is pressed.
3. if the reset button is pressed, then clear configuration and wait until the reset button will be released, after that reboot

If the gateway automatically restarts during boot, you can press and hold the reset button and on the next reboot the configuration will be cleared.

Maybe it's worth adding LED flashing to indicate the status of the reset button release waiting.

**Comment by ojousima** [comment]
Sounds good, adding to 1.2. Related to #71 #49
