### ISSUE TITLE
Missing extra information about reset reason in statistics

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#729]
![image](https://user-images.githubusercontent.com/4346875/228437902-091c8a82-bb08-4a6a-b7b6-2be40f9f0486.png)

**Comment by ojousima** [comment]
How I can verify this task without a GW that crashes?

**Comment by TheSomeMan** [comment]
> How I can verify this task without a GW that crashes?

I made a test build with a crash simulation, you can find my gateway by MAC "C8:25:2D:8E:9C:2C".
It seems to work well now:

![image](https://user-images.githubusercontent.com/4346875/234572468-a9b0fd49-f115-4144-ab9b-0e41dbfe4c4b.png)
