### ISSUE TITLE
try to feed nrf with really many bluetooth advertisements with different mac addresses to see if any issues arise

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#738]

**Comment by ojousima** [comment]
FYI, I wrote a nRF52 firmware simulating a lot of BLE devices for similar purpose a few years ago. https://ruuvi.com/fi/bluetooth-beacon-maximum-density/ The FW sent data at 100 ms per device. 

If I recall correctly, it is possible to make nRF52 violate BLE specs and sent advertisement packets with new MAC addresses every few ms. We can discuss the simulation FW further if it would be useful here
