### ISSUE TITLE
Documentation: check that documentation is up to date v 1.14

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#755]
Description:

Add new features to documentation
Publish documentation

Quickstart guide
Advanced documentation (Github)

**Comment by TheSomeMan** [comment]
@markoaamunkajo you can check the draft here: https://app.gitbook.com/o/-LsPfwGmkUWZFBz3qkE9/s/-LsPjfnhNj3v37AZtF-d/~/changes/283/ruuvi-gateway-firmware/gw-getting-started

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
@TheSomeMan remember to merge when release is rolling out

**Comment by markoaamunkajo** [comment]
Released, moving to done
