### ISSUE TITLE
tcp_transport: Stack corruption after some network errors

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#760]

**Comment by ojousima** [comment]
How to test this? 

I think a Gateway used to leak memory / crash in case the remote server returns 401 or 403, I'm not seeing that on v1.13.1-73-g2004426｜v1.0.0

**Comment by TheSomeMan** [comment]
> How to test this?
> 
> I think a Gateway used to leak memory / crash in case the remote server returns 401 or 403, I'm not seeing that on v1.13.1-73-g2004426｜v1.0.0

This problem occurs when you use HTTP protocol and an invalid server address, so it cannot be resolved.

**Comment by ojousima** [comment]
on HTTP / invalid URL I get 
```
Validation failed
HTTP response status: 400, Message: Incorrect URL: 'http://h://j9ul2'
```
on HTTP with valid, but not reservable URL https://nettest.ruuvi.com
```
Validation failed
Failed to resolve hostname
```


on MQTT I get
```
Validation failed
Failed to resolve hostname
```

The gateway UI does not crash, and according to logs it has not rebooted after a few checks. Is this tested enough or should I read logs over USB and check what there is?

**Comment by TheSomeMan** [comment]
> The gateway UI does not crash, and according to logs it has not rebooted after a few checks. Is this tested enough or should I read logs over USB and check what there is?

Yes, that's enough. In case the problem had manifested itself, the gateway would have restarted.
