### ISSUE TITLE
Independent handling of HTTP header 'Ruuvi-HMAC-KEY' for custom HTTP target

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#764]

**Comment by TheSomeMan** [comment]
@ojousima do we need to handle 'Ruuvi-HMAC-KEY' for a custom HTTP target and support independent message signing for both targets? Or it would be better to just ignore 'Ruuvi-HMAC-KEY' for non-Ruuvi targets and maybe don't send a message signature in HTTP header?

**Comment by ojousima** [comment]
I would prefer to sign message to both targets, just in case user wants to verify the authenticity of data

**Comment by ojousima** [comment]
Works with both dev and prod backends, signing verified on 2 targets
