### ISSUE TITLE
Memory leak in http_download if server returns HTTP error

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#765]

**Comment by markoaamunkajo** [comment]
You can try to enter wrong URL for custom HTTP target - "https://network.ruuvi.com/records2" and press the Check button multiple times. And check how much free memory remains (by logs). In version 1.13.1 there should be a memory leak if the server returns a text description of the error.

**Comment by markoaamunkajo** [comment]
QA passed
