### ISSUE TITLE
Configuration hotspot: Status page should be consistent between WiFi and Ethernet

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#77]
When user enters their configuration through the hotspot, the WiFi connection status remains available for the users. When they select Ethernet connection, there is no status to show that connection is successful. 

The behavior should be consistent in both cases, e.g. when user connects with Ethernet the status.json page returns the connection data. 

Before starting to work on this issue, let's decide what the exact flow should be and document it at https://docs.ruuvi.com/gw-esp32-firmware/gw-esp32-wifi-hotspot. 

@scrin @laurijamsa @TheSomeMan @nomadi FYI

**Comment by impala454** [comment]
I'll add a comment that when I arrive on the Ethernet landing page, there should be an indication to the user that they should now plug in the Ethernet cable.  It just says you've completed the configuration and that's it.
