### ISSUE TITLE
Data sending interval adjustment for MQTT target

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#775]
Description:

Data sending interval adjustment setting for MQTT target

**Comment by TheSomeMan** [comment]
@laurijamsa could you check the new UI?

![image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/4346875/000b9d26-0870-47cd-9ac2-5555b84d738f)

**Comment by laurijamsa** [comment]
Ok for this task, we will have a separate task about general configurstion wizard UI polishing.

**Comment by markoaamunkajo** [comment]
QA passed
