### ISSUE TITLE
HTTP API for refreshing whitelist/blacklist filtering

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#776]
Description:

![Image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/50437378/5df9dd28-f8ec-4763-b29a-26822f506f4f)

Estimate 10 hours

**Comment by TheSomeMan** [comment]
It was already implemented in v1.14

**Comment by markoaamunkajo** [comment]
QA passed
