### ISSUE TITLE
UI: Bluetooth scanning: Filtering checkbox not remembered if user chooses Back

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#778]
Description:

User sets filtering enabled in Bluetooth scanning page

If user chooses to go Back and then returns to this page the filtering enabled checkbox is not remembered.

https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/50437378/e6dc4506-372b-4870-8597-ba6090844ec6

**Comment by TheSomeMan** [comment]
[commit dd90ccc](https://github.com/ruuvi/ruuvi.gwui.html/pull/299/commits/dd90ccc378b8e10b982378e26e1c7650fa3f5c95)

**Comment by TheSomeMan** [comment]
Test build: https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/934/artifact/build/

**Comment by markoaamunkajo** [comment]
@TheSomeMan Tested with 934, back button works, but I tried saving

Use 1 MBit/s PHY
Use extended payload

And after saving the settings are unchecked on the filtering page.

**Comment by markoaamunkajo** [comment]
QA passed
