### ISSUE TITLE
Feature: Status page to monitor gateway health

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#78]
Let (authenticated?) users check basic statistics such as uptime, number of tags seen, bytes sent/received over WAN.

**Comment by ojousima** [comment]
It would also be possible to have a human-readable status page and a machine-readable status page, for example in Prometheus format: https://prometheus.io/docs/instrumenting/exposition_formats/

**Comment by TheSomeMan** [comment]
Closed in #100, #103
