### ISSUE TITLE
Gateway access using bearer token lost (HTTP/1.0 401 Unauthorised) after network connection loss/restore

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#780]
[Link to the forum post](https://f.ruuvi.com/t/http-kysely-ei-toimi-internet-yhteyden-katkeamisen-jalkeen/6245)

**Comment by TheSomeMan** [comment]
I have not been able to reproduce this problem. I have checked for loss of network connection over Wi-Fi and Ethernet (I tried to reboot the broadband modem). After reconnection, the "/history" request with a valid bearer token works fine. The only situation where a 401 error may be returned is when using an invalid bearer token.

**Comment by TheSomeMan** [comment]
Full erasing of the gateway settings fixed the problem: https://f.ruuvi.com/t/http-kysely-ei-toimi-internet-yhteyden-katkeamisen-jalkeen/6245/5

**Comment by markoaamunkajo** [comment]
Moving to done.
