### ISSUE TITLE
Extended payload support

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#781]
Description:

Test that it is working as expected.

**Comment by ojousima** [comment]
As of v1.14.3, I cannot see extended payload sent by nRF Connect app in the /history endpoint. The problem could be nRF Connect app / my phone, nRF inside the Gateway or ESP.

**Comment by markoaamunkajo** [comment]
Was discussed in meeting to remove extended payload support from UI options. Then this card is done.
