### ISSUE TITLE
Use Ruuvi Time Server as a last option time.ruuvi.com

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#789]
Description:

User wouldn't need to make adjustments to firewall other than ruuvi.com
We would keep current server options as secondary etc. as backup.

Would simplify initial configuration for user when no need to grant access to elsewhere beyond ruuvi.com

To be discussed in meeting

**Comment by TheSomeMan** [comment]
Add Ruuvi time server as a last optioin.

**Comment by markoaamunkajo** [comment]
QA passed
