### ISSUE TITLE
MQTT config connection bug

### ISSUE THREAD

**Issue by impala454** [ruuvi/ruuvi.gateway_esp.c#80]
When you choose MQTT, there's a bug not allowing the `mqtt_publish_table()` to occur.  I have a fix but am unable to push branches.

**Comment by impala454** [comment]
Here's a patch
```diff
diff --git a/main/uart.c b/main/uart.c
index 9e35fe9..23e7c8e 100644
--- a/main/uart.c
+++ b/main/uart.c
@@ -411,6 +411,10 @@ static void adv_post_task (void * arg)
                     ESP_LOGI (TAG, "HTTP POST: %s", json_str);
                     http_send (json_str);
                 }
+                else if (m_dongle_config.use_mqtt)
+                {
+                    flagConnected = true;
+                }
             }
         }
         else
```

**Comment by ojousima** [comment]
Hello @impala454 , thanks for the patch. You can open a pull request from your own fork or I can push this patch to some branch if you prefer to not fork the project.

**Comment by impala454** [comment]
No problem at all forking it, will do.  I just wasn't sure how the contributions from beta testers would go.

**Comment by ojousima** [comment]
Thanks for noting missing contribution instructions, I added issue #85 for them. 

In short, when opening a pull request please leave a note saying BSD-3 Licensing is ok for you and request a review from @TheSomeMan .

I'll also add a license file with BSD-3 to this repo, apparently we're not having license defined here.
