### ISSUE TITLE
nvs_partition_generator returns error: Size exceeds max allowed length `1984` bytes for key `gw_cfg_default`

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#800]
Some flags have been removed from gw_cfg_default.json as a workaround to keep within the size allowed.
Removed flags: remote_cfg_use_ssl_client_cert, remote_cfg_use_ssl_server_cert, mqtt_use_ssl_client_cert, mqtt_use_ssl_server_cert.

It looks like a bug in nvs_partition_generator because the allowed length for string values is 4000 bytes: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/nvs_flash.html#keys-and-values

Need to check if newer versions of ESP-IDF have fixed this problem.
Also, it is possible to store gw_cfg_default.json as a blob.

**Comment by TheSomeMan** [comment]
To check that this issue is fixed, you need to compare logs between two builds.
1. Previous build: https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/987/
Need to flash it manually using esptool.py (and flash gw_cfg_def.bin):
```
esptool.py esp32 -p <COM_PORT> -b 460800 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 16MB 0x8000 partition-table.bin 0xd000 ota_data_initial.bin 0x1000 bootloader.bin 0x100000 ruuvi_gateway_esp.bin 0x500000 fatfs_gwui.bin 0x5C0000 fatfs_nrf52.bin 0xB00000 gw_cfg_def.bin
```
2. Next build: https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/988/
Flash it with the same command.

In the logs for the previous build, you'll see warning messages like "Can't find key 'remote_cfg_use_ssl_client_cert' in config-json":
```
I (3013) terminal_log: -----DEVICE_ID-----

I (3017) terminal_log: ID: c2:fd:b7:b2:e4:0a:46:b1

I (3023) terminal_log: ADDR: ad:4f:fe:16:d9:f4:00:00

I (3098) ruuvi_gateway: [main/1] ### Deinit gw_cfg
I (3100) gw_cfg: [main/1] Read default gw_cfg from NVS by key 'gw_cfg_default'
I (3100) gw_cfg: [main/1] Read file 'gw_cfg_default' from NVS
I (3108) gw_cfg: [main/1] File 'gw_cfg_default' was successfully read from NVS
 (3114) gw_cfg: [main/1] Default gw_cfg was successfully read from NVS
W (3124) gw_cfg: [main/1] Can't find key 'remote_cfg_use_ssl_client_cert' in config-json
W (3131) gw_cfg: [main/1] Can't find key 'remote_cfg_use_ssl_server_cert' in config-json
W (3142) gw_cfg: [main/1] Key 'mqtt_prefix' is empty in config-json, use default value: 
```

P.S. I found out that 'gw_cfg_def.bin' is missing on Jenkins. I fixed it and 'gw_cfg_def.bin' will be saved starting from the next build.
Here are the missing files:
[gw_cfg_def_1.zip](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/12023010/gw_cfg_def_1.zip)
[gw_cfg_def_2.zip](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/12023012/gw_cfg_def_2.zip)

**Comment by markoaamunkajo** [comment]
QA passed
