### ISSUE TITLE
Replace cJSON library for json generation with async sequential generator library

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#804]
This is needed for HTTP(S) targets and the "/history" API because cJSON tries to allocate a large buffer for the whole json representation and then for the json string. If you have a large number of sensors, this may result in a lack of memory.

**Comment by laurijamsa** [comment]
In the meeting we agreed that Gateway will have only one /history with decoded data in it

**Comment by TheSomeMan** [comment]
@markoaamunkajo To test, you need to check advs delivery in Ruuvi Cloud or custom HTTP(s) target. Also, check requests "/history" and "/history?decode=true", "/history?decode=false"

**Comment by markoaamunkajo** [comment]
QA passed
