### ISSUE TITLE
ESP32 USB connection is not reliable

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#81]
On macOS 10.15.5 with esptool USB connection cannot be always established. The command fails more than 50% of the times.

A successful log:

```l@Ls-MacBook ~ % esptool.py flash_id
esptool.py v2.8
Found 3 serial ports
Serial port /dev/cu.usbserial-1410
Connecting........_____....._
Detecting chip type... ESP32
Chip is ESP32D0WDQ5 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 24:0a:c4:e2:af:94
Uploading stub...
Running stub...
Stub running...
Manufacturer: ef
Device: 4018
Detected flash size: 16MB
Hard resetting via RTS pin...
````
A successful log with a second hardware unit:

```l@Ls-MacBook ~ % esptool.py flash_id
esptool.py v2.8
Found 3 serial ports
Serial port /dev/cu.usbserial-1410
Connecting........_____....._____....._____....._____....._____....._____.....__
Detecting chip type... ESP32
Chip is ESP32D0WDQ5 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 24:0a:c4:e3:2e:b0
Uploading stub...
Running stub...
Stub running...
Manufacturer: ef
Device: 4018
Detected flash size: 16MB
Hard resetting via RTS pin...
```

Unsuccessful logs:

```l@Ls-MacBook ~ % esptool.py flash_id
esptool.py v2.8
Found 3 serial ports
Serial port /dev/cu.usbserial-1410
Connecting........_____....._____....._____....._____....._____....._____....._____
/dev/cu.usbserial-1410 failed to connect: Failed to connect to Espressif device: Invalid head of packet (0x71)
``` 

```l@Ls-MacBook ~ % esptool.py flash_id
esptool.py v2.8
Found 3 serial ports
Serial port /dev/cu.usbserial-1410
Connecting........_____....._____....._____....._____....._____....._____....._____
/dev/cu.usbserial-1410 failed to connect: Failed to connect to Espressif device: Invalid head of packet (0x20)
``` 

```l@Ls-MacBook ~ % esptool.py flash_id
esptool.py v2.8
Found 3 serial ports
Serial port /dev/cu.usbserial-1410
Connecting........_____....._____....._____....._____....._____....._____....._____
/dev/cu.usbserial-1410 failed to connect: Failed to connect to Espressif device: Invalid head of packet (0x0A)
``` 

Steps to (potentially) reproduce the issue:

1) Install Homebrew
2) brew install esptool
3) esptool.py flash_id
4) Wait the tool to scan the found ports

**Comment by ojousima** [comment]
I think this is more of a hardware issue, maybe the esptool speed should be dialed down? https://github.com/espressif/esptool#baud-rate

**Comment by laurijamsa** [comment]
"The baud rate is limited to 115200 when esptool.py establishes the initial connection, higher speeds are only used for data transfers." no help with that. But I will report back later if will or won't find a solution on this.

**Comment by ojousima** [comment]
Let's wait for further information, so far you're only one who's been reporting this issue.

**Comment by ojousima** [comment]
@laurijamsa any updates? Can we close this issue as so far you're only one who has been reporting it?

**Comment by laurijamsa** [comment]
I just confirmed that this error is most probably not related to Ruuvi Gateway boards but my MacBook only.

Test procedure:

Try 2 different Gateway hardwares on macOS. On the both, esptool.py occasionally returns the same invalid head of packet error.

Try the same boards on a Ubuntu 20.04 LTS machine. Able to run the command ~50 times on the both boards without a single error.

**Comment by TheSomeMan** [comment]
@laurijamsa, couple of years ago I faced with a similar problem on Win platform.
Increased timeouts allowed to get rid of the problem.
I attached a patched esptool.py with increased timeouts, you can try it, I hope it will help.
[esptool.zip](https://github.com/ruuvi/ruuvi.gateway_esp.c/files/5345042/esptool.zip)

**Comment by laurijamsa** [comment]
@TheSomeMan Thanks for the tip. I tried the patched esptool.py but it had no effect on this issue. Still getting sometimes invalid head of packet errors and even when not, detecting the ESP32 is slow...
