### ISSUE TITLE
Automatically install firmware updates on RuuviTags

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#810]
1. First, we need to implement support in the RuuviTags firmware.
2. User must manually enable this feature during initial sensor initialization.
3. A secret private key (RSA or ECC) must be used to sign RuuviTag firmware.
4. RuuviTag firmware must contain a public key (RSA or ECC) that is used to verify the firmware signature and allows only signed firmware to be installed.

**Comment by laurijamsa** [comment]
Idea is good but due to its complexity we will not be implementing it for now. But this can stay in proposals for sure for future consideration.
