### ISSUE TITLE
Decode data in API "/history" by default

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#828]

**Comment by markoaamunkajo** [comment]
@TheSomeMan this is checked at /history URL, I already see that values are decoded in build 1031
Can be closed?

**Comment by TheSomeMan** [comment]
> @TheSomeMan this is checked at /history URL, I already see that values are decoded in build 1031 Can be moved to done?

Yes, sure

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
@TheSomeMan 
Does it also support df 3, df5, etc

Maybe this should be mentioned in advanced documentation?

**Comment by TheSomeMan** [comment]
> Maybe this should be mentioned in advanced documentation?

It is documented here: https://app.gitbook.com/o/-LsPfwGmkUWZFBz3qkE9/s/-LsPjfnhNj3v37AZtF-d/~/changes/283/gw-data-formats/http-get-history-with-timestamps-and-decoding

![image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/4346875/7699b793-4d06-4ed4-8c69-79a90cacf9cb)

**Comment by markoaamunkajo** [comment]
QA passed
