### ISSUE TITLE
Layout issues mobile

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/ruuvi.gateway_esp.c#832]
Description:

I will collect here layout issues spotted in mobile

**Comment by markoaamunkajo** [comment]
Android Chrome pages scrolled not to the top



![Image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/50437378/211647f2-cf12-406f-b835-4a4d7a1c2c2a)
![Image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/50437378/eaf6acc9-74db-464b-bf29-bcc87db6d657)
![Image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/50437378/385810af-15e9-418d-a28d-d9998f53e50b)
![Image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/50437378/4b56eccc-01a5-4338-bdb2-788cb606e747)
![Image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/50437378/7bd2783a-154f-4996-ae4a-b848481ceefa)
![Image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/50437378/5f6ca3cb-1578-46ac-b3be-7cb7992b5f25)
![Image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/50437378/bb1cb306-cf7a-4ba3-8987-551c244d30f8)
![Image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/50437378/6fbfb6c6-b041-40f9-98f8-8621f42c633b)

**Comment by TheSomeMan** [comment]
@markoaamunkajo how would you recommend redesigning UI to solve this issue?

![image](https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/4346875/173ef8ff-ee14-475e-9da4-b939099a03e9)

**Comment by markoaamunkajo** [comment]
@TheSomeMan is there a way to have the cursor to be shown at the end of the text?

**Comment by TheSomeMan** [comment]
> @TheSomeMan is there a way to have the cursor to be shown at the end of the text?

Yes, I think it's possible, I'll do it.

**Comment by TheSomeMan** [comment]
> @TheSomeMan is there a way to have the cursor to be shown at the end of the text?

I have implemented putting the cursor at the end of the bearer token input field after the token is generated.
But after the input field loses focus the text is scrolled left to the beginning of the string. This is standard browser behavior and it cannot be changed.

**Comment by markoaamunkajo** [comment]
This is ok for me. Looks much better.

The pages are not still scrolling to top as reported before. Some pages are left a bit from the top. I am expecting to see the top title when moving between pages so page scrolled to full top.

**Comment by markoaamunkajo** [comment]
QA passed

**Comment by markoaamunkajo** [comment]
@TheSomeMan I see Android Chrome could still be improved. It was not scrolled to top on these pages


- Setup Wizard
- Software Update

when I recorded the video.


https://github.com/ruuvi/ruuvi.gateway_esp.c/assets/50437378/b7ea7a5c-146b-4adb-abef-dd9e93f6a08b

**Comment by markoaamunkajo** [comment]
QA passed
