### ISSUE TITLE
After connecting to a network successfully, it's not clear for the user that the configuration is now completed

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi.gateway_esp.c#84]
Make it more clear that everything is now working and it is ok to disconnect from the hotspot.

Maybe add a button on the last page that says "Complete the setup and shut down the configuration hotspot" and then ESP32 would reboot automatically.

Currently, it is not really clear for the user that what has to be done after connected to a WiFi network.

**Comment by DG12** [comment]
version 1.3.1 reports "Ruuvi Gateway is now ready to be used."
