### ISSUE TITLE
Filter out duplicate messages

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#854]
Ruuvi sensors can send the same message (with the same "measurementSequenceNumber") multiple times. Such messages are not a big problem for periodic HTTP relaying, but they might be a problem for immediate MQTT relaying because they increase MQTT traffic by transmitting duplicate messages.
This is crucial for #659 to prevent ping-ponging in case of multiple Gateways working in range extender mode.

**Comment by markoaamunkajo** [comment]
QA passed
