### ISSUE TITLE
Problem with Gateway configuration via Nginx proxy manager

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#868]
Kirbo  [5:32 PM]
Hi, I just found out I cannot login into the Ruuvi Gateway behind a proxy. I think this might have been done on purpose, but "as a user, I'd like to be enabled to allow login from behind proxy", i.e. allow login from behind proxy/allow login from list of origins/idk.
I'm currently using Nginx Proxy Manager (https://nginxproxymanager.com/), which both adds SSL certificates to my local URLs and redirects e.g. https://ruuvi.hima.osoite.com/ into http://192.168.1.130/ (so I don't need to remember the IP-addresses and ports for like 20 different local services that I'm currently running (which pretty much every one of them uses a different port: 80, 81, 443, 3000, 4408, 4409, 8006, 8080, 8081, 8123, 8888, 9000, 10086...).
The login itself opens up as it should, but the response I get from the POST /auth endpoint is 401. If I open the login via the direct IP-address for the Gateway, I am able to login without issues.
Disclaimer: I could also have wrong settings in "NPM", but here are few screenshots anyway, if it helps you somehow
(..and no, the URLs are not accessible outside of my LAN, but still wanted to redact them. In case anyone is interested, my router advertises for LAN clients to use the AdGuard Home as DNS-server, which has a wildcard custom DNS-rewrite for *.[hima.osoite.com](http://hima.osoite.com/) -> 192.168.1.9, which is the IP-address for the "NPM", which then uses the Proxy Pass to redirect the [ruuvi.hima.osoite.com](http://ruuvi.hima.osoite.com/) -> 192.168.1.130:80)

**Comment by TheSomeMan** [comment]
The reason for the problem is that Nginx is stripping the 'ruuvi_ecdh_pub_key' from HTTP header because this key contains underscores.
We can easily fix this by renaming the key to "Ruuvi-Ecdh-Pub-Key".
As a workaround users can configure Nginx to allow headers with underscores using the underscores_in_headers directive:
```
underscores_in_headers on;
```

**Comment by ojousima** [comment]
> We can easily fix this by renaming the key to "Ruuvi-Ecdh-Pub-Key".

Is there some kind of a standard that frowns on underscores in headers? If so, we should do the change. 

On the other hand, I'm not aware of any community tool that would be using the encrypted hotspot, so we might be able to do the change in any case without impacting existing users

**Comment by TheSomeMan** [comment]
> Is there some kind of a standard that frowns on underscores in headers?

```
The RFC 7230, which is part of the HTTP/1.1 specification, defines the syntax for header fields. According to the RFC, a header field name should conform to the token syntax, which is defined as a series of characters from a limited set, excluding certain delimiters including the underscore (_). 
```

**Comment by ojousima** [comment]
Let's go ahead with changing the `_` to `-` then

**Comment by ojousima** [comment]
For some reason my nginx prexy manager does not create SSL certificate for me, but I can access the Gateway through HTTP routed through nginx reverse proxy. Is this comprehensive enough test or do we need to check SSL as well?

**Comment by TheSomeMan** [comment]
> Is this comprehensive enough test or do we need to check SSL as well?

Yes, testing over HTTPS is also necessary because in this mode Ngnix Proxy converts all key names in the HTTP header to lowercase.
Here is the bugfix for this problem: https://github.com/ruuvi/esp32-wifi-manager/issues/265
