### ISSUE TITLE
Ruuvi sensors only option not taking

### ISSUE THREAD

**Issue by impala454** [ruuvi/ruuvi.gateway_esp.c#87]
In the set up, when I select `Ruuvi sensors only` from the `Which devices to scan` screen, it doesn't seem to take.  When I run the monitor, I notice the company id is set to Ruuvi's ID, but the variable `company_filter` in the code stays `0`.  The effect is the filter by Ruuvi sensors only doesn't work, it still finds and publishes all devices it finds.

This log comes from the `ruuvidongle_main.c` function `ruuvi_send_nrf_settings()`:
```
I (724) settings: config: company id: 0x0499
I (734) ruuvidongle: sending settings to NRF: use filter: 0, company id: 0x0499
```

I also short circuited that first statement just to see if the filter worked at all by doing: 

```cpp
void ruuvi_send_nrf_settings (struct dongle_config * config)
{
    ESP_LOGI (TAG, "sending settings to NRF: use filter: %d, company id: 0x%04x",
              config->company_filter, config->company_id);

    // if (config->company_filter)
    if (true)
    {
        uart_send_nrf_command (SET_FILTER, &config->company_id);
    }
    else
    {
        uart_send_nrf_command (CLEAR_FILTER, 0);
    }
}
```

And it still didn't seem to filter out only the Ruuvi tags (definitely more tags scanned than I have in my house).

**Comment by ojousima** [comment]
Yes, this is a work in progress. Filtering is not implemented yet on nRF52.

**Comment by impala454** [comment]
Ah ok, gotcha.  It still does seem like there may be an issue with the web interface's options not passing into the config struct though.
