### ISSUE TITLE
Error description with the message from the server during URL validation contains excessive escaping

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#927]

**Comment by TheSomeMan** [comment]
In order to test it, you need to enable custom HTTPS and try to check URL "https://network.ruuvi.com/record2". The server will return an error message like this:
```
{"message":"Not Found"}
```

This message should be properly escaped when displaying in UI:
```
HTTP response status: 404, Message from the server: {"message":"Not Found"}
```


The previous build generated extra escaping like this:
```
HTTP response status: 404, Message from the server: {\"message\":\"Not Found\"}
```

**Comment by markoaamunkajo** [comment]
QA passed
