### ISSUE TITLE
Static IP configuration for Ethernet is not saved

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#935]

**Comment by TheSomeMan** [comment]
To test it you need to start Wi-Fi AP and configure Gateway to use Ethernet, then disable DHCP and set some IP address from your local network. After configuration is complete check the IP address displayed on the last page, then try to ping Gateway using new IP address.

**Comment by markoaamunkajo** [comment]
QA passed
