### ISSUE TITLE
Hotspot: Custom HTTP/MQTT settings not shown by default. 

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvi.gateway_esp.c#95]
A previous custom configuration does not show settings unless radio box is selected to other option and back. 
![image](https://user-images.githubusercontent.com/2360368/89102961-c6ecd400-d416-11ea-90e7-1f5517c17500.png)

**Comment by TheSomeMan** [comment]
I tested it and it works as expected on the current version.
