### ISSUE TITLE
mqtt_client: incorrect error code is printed to log if esp_transport_read returns error

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/ruuvi.gateway_esp.c#986]

**Comment by TheSomeMan** [comment]
For testing, you need to configure the gateway for MQTT on AWS and enable retained messages. In the logs, you should see the correct error code (-1) in the log message prefixed with "mqtt_message_receive: transport_read() error: "

**Comment by markoaamunkajo** [comment]
This for @ojousima too because of AWS
